const Belarus = [
    {
        _id: '1',
        nameUrl: 'belarus-1221-3',
        productHeader: 'Belarus 1221.3',
        className: `belarus-1221-img`,
        desc1: 'Traktor je dizajniran za razne poljoprivredne operacije sa montiranim, polu montiranim i vučenim mašinama.',
        desc2: 'Traktor je dizajniran za razne poljoprivredne operacije sa montiranim, polu montiranim i vučenim mašinama. Dizel motor je u skladu sa ekološkim zahtevima II stepena prema emisiji opasnih materija.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Belarus 1221.3',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'D-260.2 S2; 100 / 136',
            'Broj cilindara',
            '6',
            'Zapremina motora u cm3',
            '7200',
            'Pumpa za ubrizgavanje goriva',
            'Linijska',
            'Sistem za hlađenje motora ',
            'voda – antifriz',
            'Menjač',
            'sinhronizovan sa reduktorom',
            'Broj stepena prenosa, napred/nazad ',
            '16 / 8',
            'Priključno vratilo nezavisno, o/min ',
            ' 540 i 1000',
            'Kapacitet podizanja na krajevima poluga u kg',
            '4500',
            'Dimenzije guma: prednje / zadnje',
            '420/70- R 24 / 18,4 R 38',
            'Težina sa balastom u kg  ',
            '5570',
            'Zapremina rezervoara za gorivo u litrama ',
            '160',
            'Dimenzije; dužina / širina / visina, u cm ',
            '4950 / 1970 / 2820 (vrh kabine)',
            'Klirens u mm',
            '620',
            'Klima ',
            'opcija',
            'Upravljač ',
            'hidraulični',

        ]
    },
    {
        _id: '2',
        nameUrl: 'belarus-1021.3',
        productHeader: 'Belarus 1021.3',
        className: `belarus-1021-img`,
        desc1: 'Prednja pogonska osovina sa planetarnim grupnim zupčanicima, zadnja osovina sa planetarnim završnim pogonima.',
        desc2: 'Prednja pogonska osovina sa planetarnim grupnim zupčanicima, zadnja osovina sa planetarnim završnim pogonima.Traktori su namenjeni za razne poljoprivredne operacije sa montiranim, polu montiranim i vučenim mašinama i uređajima, za vuču.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Belarus 1021.3',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'D-245 S2; 81 / 110',
            'Broj cilindara',
            ' 4',
            'Zapremina motora u cm3',
            '4750',
            'Pumpa za ubrizgavanje goriva',
            'Linijska',
            'Sistem za hlađenje motora ',
            'voda – antifriz',
            'Menjač',
            'sinhronizovan',
            'Broj stepena prenosa, napred/nazad ',
            '14 / 4',
            'Priključno vratilo nezavisno, o/min ',
            ' 540 i 1000',
            'Kapacitet podizanja na krajevima poluga u kg',
            '4530',
            'Dimenzije guma: prednje / zadnje',
            '360/70-R 24 / 16,9 R 38',
            'Težina sa balastom u kg  ',
            '5128',
            'Zapremina rezervoara za gorivo u litrama ',
            '150',
            'Dimenzije; dužina / širina / visina, u cm ',
            ' 4190 / 2250 / 2840 (vrh kabine)',
            'Klirens u mm',
            '645',
            'Klima ',
            'opcija',
            'Upravljač ',
            'hidraulični',
        ],

    },
    {
        _id: '3',
        nameUrl: 'belarus-1021-mb',
        productHeader: 'Belarus 1021MB',
        className: `belarus-1021mb-img`,
        desc1: 'Prednja pogonska osovina sa planetarnim grupnim zupčanicima, zadnja osovina sa planetarnim završnim pogonima.',
        desc2: 'Prednja pogonska osovina sa planetarnim grupnim zupčanicima, zadnja osovina sa planetarnim završnim pogonima.Traktori su namenjeni za razne poljoprivredne operacije sa montiranim, polu montiranim i vučenim mašinama i uređajima, za vuču.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Belarus 1021MB',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'D-245; 77 / 105',
            'Broj cilindara',
            ' 4',
            'Zapremina motora u cm3',
            '4750',
            'Pumpa za ubrizgavanje goriva',
            'Linijska',
            'Sistem za hlađenje motora ',
            'voda – antifriz',
            'Menjač',
            'sinhronizovan',
            'Broj stepena prenosa, napred/nazad ',
            '14 / 4',
            'Priključno vratilo nezavisno, o/min ',
            ' 540 i 1000',
            'Kapacitet podizanja na krajevima poluga u kg',
            '4530',
            'Dimenzije guma: prednje / zadnje',
            '360/70-24 / 16,9 R 38',
            'Težina sa balastom u kg  ',
            '5085',
            'Zapremina rezervoara za gorivo u litrama ',
            '150',
            'Dimenzije; dužina / širina / visina, u cm ',
            '4150 / 2250 / 2840 (vrh kabine)',
            'Klirens u mm',
            '645',
            'Klima ',
            'opcija',
            'Upravljač ',
            'hidraulični',
        ],

    },
    {
        _id: '4',
        nameUrl: 'belarus-892-rm',
        productHeader: 'Belarus 892 RM',
        className: `belarus-892rm-img`,
        desc1: 'Traktor sa prednjom pogonskom osovinom sa planetarno-ostružnim zupčanicima. Ekološki standard Faza 0.',
        desc2: 'Traktor sa prednjom pogonskom osovinom sa planetarno-ostružnim zupčanicima. Ekološki standard Faza 0.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Belarus 892 RM',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'D-245.5; 66 / 90',
            'Broj cilindara',
            ' 4',
            'Zapremina motora u cm3',
            '4750',
            'Pumpa za ubrizgavanje goriva',
            'Linijska',
            'Sistem za hlađenje motora ',
            'voda – antifriz',
            'Menjač',
            'mehanički sa reduktorom',
            'Broj stepena prenosa, napred/nazad ',
            '18 / 4',
            'Priključno vratilo nezavisno, o/min ',
            ' 540 i 1000',
            'Kapacitet podizanja na krajevima poluga u kg',
            '4300',
            'Dimenzije guma: prednje / zadnje',
            '360/70-24 / 18,4 R 34',
            'Težina sa balastom u kg  ',
            '4345',
            'Zapremina rezervoara za gorivo u litrama ',
            '130',
            'Dimenzije; dužina / širina / visina, u cm ',
            '3930 / 1970 / 2785 (vrh kabine)',
            'Klirens u mm',
            '510',
            'Klima ',
            'opcija',
            'Upravljač ',
            'hidraulični',
        ],

    },
    {
        _id: '5',
        nameUrl: 'belarus-820-rm',
        productHeader: 'Belarus 820 RM',
        className: `belarus-820rm-img`,
        desc1: 'Traktor sa prednjom pogonskom osovinom sa planetarno-ostružnim zupčanicima. Ekološki standard Faza 0.',
        desc2: 'Traktor sa prednjom pogonskom osovinom sa planetarno-ostružnim zupčanicima. Ekološki standard Faza 0.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Belarus 820 RM',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'D-243; 60 / 81',
            'Broj cilindara',
            ' 4',
            'Zapremina motora u cm3',
            '4750',
            'Pumpa za ubrizgavanje goriva',
            'Linijska',
            'Sistem za hlađenje motora ',
            'voda – antifriz',
            'Menjač',
            'mehanički sa reduktorom',
            'Broj stepena prenosa, napred/nazad ',
            '18 / 4',
            'Priključno vratilo nezavisno, o/min ',
            ' 540 i 1000',
            'Kapacitet podizanja na krajevima poluga u kg',
            '3500',
            'Dimenzije guma: prednje / zadnje',
            '360/70-24 / 18,4 R34',
            'Težina sa balastom u kg  ',
            '4350',
            'Zapremina rezervoara za gorivo u litrama ',
            '130',
            'Dimenzije; dužina / širina / visina, u cm ',
            '3930 / 1970 / 2785 (vrh kabine)',
            'Klirens u mm',
            '510',
            'Oprema ',
            'klopljen motor, klateća poteznica',
            'Upravljač ',
            'hidraulični',
        ],

    },
    {
        _id: '6',
        nameUrl: 'belarus-82-1',
        productHeader: 'Belarus 82.1',
        className: `belarus-82-img`,
        desc1: 'Daljinski cilindar, sa hidrauličnim podizačem koji omogućava gaz, položaj, mešanje i podešavanje visine položaja.',
        desc2: 'Daljinski cilindar, sa hidrauličnim podizačem koji omogućava gaz, položaj, mešanje i podešavanje visine položaja.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Belarus 82.1',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'D-243; Nominalna snaga 60 / 81; Eksploataciona-homologizovana snaga 57,8 / 79',
            'Broj cilindara',
            ' 4',
            'Zapremina motora u cm3',
            '4750',
            'Pumpa za ubrizgavanje goriva',
            'Linijska',
            'Sistem za hlađenje motora ',
            'voda – antifriz',
            'Menjač',
            'mehanički sa reduktorom',
            'Broj stepena prenosa, napred/nazad ',
            '18 / 4',
            'Priključno vratilo nezavisno, o/min ',
            ' 540 i 1000',
            'Kapacitet podizanja na krajevima poluga u kg',
            '3500',
            'Dimenzije guma: prednje / zadnje',
            '11,2-20 / 15,5R 38',
            'Težina sa balastom u kg  ',
            ' 4100',
            'Zapremina rezervoara za gorivo u litrama ',
            '130',
            'Dimenzije; dužina / širina / visina, u cm ',
            '3930 / 1970 / 2785 (vrh kabine)',
            'Klirens u mm',
            '645',
            'Klima  ',
            'opcija',
            'Upravljač ',
            'hidraulični',
        ],
    },
]


export const both = [...Belarus];
export { Belarus }