const Solis = [
    {
        _id: '1',
        nameUrl: 'solis-26',
        productHeader: 'Solis 26',
        className: `solis-26-img`,
        desc1: 'Izuzetno izdržljiva SOLIS kompaktna serija, koja je oličenje moći, efikasnosti kao i vrhunskog dizajna.',
        desc2: 'Izuzetno izdržljiva SOLIS kompaktna serija, koja je oličenje moći, efikasnosti kao i vrhunskog dizajna, može biti opremljena sa kompletnom paletom priključaka za svestrano obavljanje poslova u poljoprivrede i komunalnoj delatnosti.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 26',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            'Mitsubhishi',
            'Tip motora',
            'Četvorotaktni sa direktnim ubrizgavanjem',
            'Kategorija (ks)',
            '26',
            'Snaga (kW)',
            '19,80',
            'Radna brzina (cc)/broj cilindara',
            '1318/3',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Mehanički – 6 napred + 2 nazad',
            'Maksimalna brzina (km/h)',
            '17,05',
            'Priključno vratilo ',
            '540/750/1000',
            'Upravljač ',
            'Hidraulični',
            'Sila dizanja hidraulike (kg)',
            '600',
            'Izvod za hidrauliku',
            '2 Dvosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '6.00×12/8.30×20',
            'Međuosovinsko rastojanje (mm)',
            '1560',
            'Dimenzije (DxŠxV)',
            '2705x1058x2153',
            'Težina – bez kabine/sa kabinom (kg)',
            '960'
        ],

        standardnaOprema: 'Opis Proizvoda',
        standardLi: [
            ' - Opcija sa i bez kabine',
            ' - Pogon na sva 4 točka',
            ' - Motor i konstrukcija - Mitshubhishi ( Japan )',
            ' - Hidraulični sistem MITA ( Italija )',
            ' - Ekonomičan i jednostavan za korišćenje',
        ],

    },
    {
        _id: '2',
        nameUrl: 'solis-20',
        productHeader: 'Solis 20',
        className: `solis-20-img`,
        desc1: 'Solis 20 su mali traktori posebno namenjenii za rad u ograničenom i uskom prostoru. Solis 20..',
        desc2: 'SOLIS 20 su mali traktori posebno namenjenii za rad u ograničenom i uskom prostoru u povrtarstvu, staklenicima, voćarstvu i vinogradarstvu, a pored toga, pogodni su za univerzalnu primenu na manjim posedima, komunalne radove i transport . Poseduju priključne tačke I kategorije i na njih je moguće priključiti veći broj priključaka, kao što su: freza, plug, tanjirača, kultivator, kosačica, sakupljač sena, prikolica, rasipač đubriva, i slično. Zahvaljujući Mitsubishi motoru i optimalnoj konstrukciji ovi traktori pružaju izvrsne manevarske sposobnosti uz izuzetnu lakoću korišćenja.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 20',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            'Mitsubhishi MVL 3 E',
            'Tip motora',
            'četvorotaktni,dizel',
            'Kategorija (ks)',
            '20',
            'Snaga (kW)',
            '13,4',
            'Radna brzina (cc)/broj cilindara',
            '952',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Broj cilindara',
            '3',
            'Prečnik cilindra/hod klipa (mm)',
            '76/70',
            'Nominalni broj obrtaja (o/min)',
            '2700',
            'Maksimalni obrtni moment (Nm) ',
            '52,3 pri 2000 o/min',
            'Filter vazduha',
            'Uljni',
            'Pumpa za ubrizgavanje goriva / dizne',
            'Denso / Denso (Japan)',
            'Radni pritisak ulja (bar)',
            '3-4',
            'Kompresioni odnos',
            '23:1',
            'Grejač(hladan start)/tip',
            'DA,na svakom cilindru',
            'Tip Menjača',
            'Mehanički (klizni)',
            'Broj stepeni prenosa',
            '6N+2R',
            'Odnos stepena prenosa i brzine (km/h) - napred',
            'S I-1.25; S II-1.88; S III-3.17 | B I-5.50; B II-8.28; B III13.93',
            'Odnos stepena prenosa i brzine (km/h) - nazad',
            'S I-1,60, B I-7,03',
            'Maksimalna brzina (km/h)',
            '15.58',
            'Blokada diferencijala',
            'DA',
            'Tip Kvačila',
            'Jednostepeno, suvo',
            'Vrsta lamele - pogonska / priključno vratilo',
            'Azbestna',
            'Tip Priključnog vratila',
            'Nezavisno',
            'Broj obrtaja(o/min)',
            '628/931/1588 pri 2700 o/min',
            'Broj žljebova',
            '6',
            'Maksimalna snaga(KS)',
            '13.2',
            'Tip Kočnica',
            'Mahaničke(dobši)',
            'Parkirna kočnica',
            'DA',
            'Kocnica za prikolicu',
            'NE',
            'Tip Upravljača',
            'Mahanički',
            'Radijus zakretanja(m)',
            '2.3',
            'Hidraulični sistem - sila dizanja(kg)',
            '500',
            'Tip pumpe',
            'Zupčasta( MITA)',
            'Kapacite pumpe (I/min)',
            '13',
            'Opcije podešavanja',
            'Položaja',
            'Kačenje u tri tačke',
            'Kategorija I',
            'Izvod za hidrauliku',
            '1-Jednosmerni',
            'Akumulator',
            '12V,45A',
            'Elektrostarter(Alnaser)',
            '12V,1.6KW',
            'Alternator',
            '12V,20Ah',
            'Sirena',
            'DA',
            'Sedmopolni priključak',
            'DA',
            'Kutija sa osiguračima',
            'DA',
            'Sigurnosni prekidač menjača',
            'DA',
            'Sigurnosni prekidač kvačila',
            'NE',
            'Sigurnosni prekidač priključnog vratila',
            'NE',
            'Svetla',
            'Prednji farovi, pozicije sa migavcima, sva četiri migavca, zadnja( stop, migavci, pozicije), za registarsku tablicu.',
            'Instrument tabla',
            'Merač temperature rashladne tečnosti, merač pritiska ulja u motoru, merač (broja obrtaja motora-časova rada), merač goriva u rezervoaru, indikator punjenja akumulatora, duga svetla, migavci levi/desni, pokazivač stepena priključnog vratila.',
            'Prednje Gume',
            '5.0×12',
            'Zadnje Gume',
            '8.0×18',
            'Pritisak-prednje(bar)',
            '1,75 za njivu | 2,15 za put',
            'Pritisak-zadnje(bar)',
            ' 0,84 za njivu | 1,57 za put',
            'Međuosovinsko rastojanje(mm)',
            '1420',
            'Ukupna dužina(mm)',
            '2310',
            'Ukupna širina(mm)',
            '950',
            'Visina sa sigurnosnim ramom(mm)',
            '1950',
            'Prednja osovina(mm)',
            '195',
            'Izmedju osovina(mm)',
            '250',
            'Zadnja osovina(mm)',
            '205',
            'Širina traga prednjih točkova(mm)',
            '820',
            'Širina traga zadnjih točkova(mm)',
            '725',
            'Težina (kg)',
            '885',
            'Rezervoar za gorivo (lit)-bez kabine/sa kabinom',
            '30',
            'Rashladna tečnost u motoru (lit)',
            '14',
            'Ulje u motoru (lit)',
            '3.6',
            'Ulje u transmisiji(menjac,diferencijal i hidraulika) (lit)',
            '17',
            'Ulje u servo upravljaču (lit)',
            'NE',
            'Ulje u prednjem mostu (lit)',
            '2',
            'Ulje u reduktoru prednje osovine (lit)',
            '0.5',
            'Sigurnosni ram',
            'DA',
            'Topling',
            'DA',
            'Set rezervnih delova',
            'DA',
            'Set alata',
            'DA',
            'Retrovizori-levi/desni',
            'DA,sa obe strane',
            'Horizontalni auspuh',
            'DA',
            'Tegovi-prednji/zadnji(kg)',
            'DA,napred 4X10',
            'Rotaciono svetlo',
            'DA',
        ],

        standardnaOprema: 'Prednosti',
        standardLi: [
            ' - Garancija 3 godine ili 2000 radnih sati',
            ' - Homologovan u skladu sa evropskim normama',
            ' - Mitsubishi motor i konstrukcija',
            ' - Pumpa visokog pritiska i dizne DENSO (Japan)',
            ' - Pogon na sva 4 točka, sa mogućnošću korišćenja samo zadnje vuče',
            ' - Hidraulični sistem MITA(Italija)',
            ' - Ekonomičan i jednostavan za korišćenje',
            ' - Set rezervnih delova i alata',
            ' - Dva besplatna servisa',

        ],

    },
    {
        _id: '3',
        nameUrl: 'solis-60nt',
        productHeader: 'Solis 60NT',
        className: `solis-60nt-img`,
        desc1: 'Namenjeni za korišćenje u poljoprivredi, komunalne radove i transport uz lakoću rada.',
        desc2: 'SOLIS N serija sa uskim razmakom između točkova, garantuje maksimalne performanse u primeni u voćarstvu i vinogradarstvu. Sinhronizovana transmisija kod ove serije obezbeđuje lakoću rada uz visoku produktivnost.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 60NT',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            '4100 FL',
            'Tip motora',
            'Četvorotaktni sa direktnim ubrizgavanjem',
            'Kategorija (ks)',
            '60',
            'Snaga (kW)',
            '44.2',
            'Radna zapremina cc/ broj cilindara',
            '3707 / 4',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Sinhroni 12napred + 12 nazad',
            'Maksimalna brzina (km/h)',
            '31.1',
            'Tip kvačila',
            'Dvostruko',
            'Priključno vratilo ',
            'Nezavisno/sinhronizovano ( 540-750 o/min )',
            'Kočnice',
            'Diskovi u ulju',
            'Upravljač',
            'Hidraulični',
            'Sila dizanja hidraulike ( kg )',
            '2500',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 2 Jednosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '8 x 18 / 14.9 x 24',
            'Međuosovinsko rastojanje (mm)',
            '2216',
            'Dimenzije sa kabinom (DxŠxV-mm) ',
            '4150 x 1475 x 2310',
            'Težina bez kabine/sa kabinom (kg)',
            '2640/2880',
        ],

        standardnaOprema: 'Opis Proizvoda',
        standardLi: [
            ' - Keramička lamela',
            ' - Planetarni reduktori',
            ' - Sinhro menjač ( 12+12 brzina )',
            ' - Hidraulični sistem MITA ( Italija )',
            ' - Niska potrošnja goriva',
            ' - Opcija sa i bez kabine',
            ' - Pumpa visokog pritiska i dizne – BOSCH',
            ' - Transmisija i prednji most CARRARO ( Italija )',
        ],

    },
    {
        _id: '4',
        nameUrl: 'solis-75nt',
        productHeader: 'Solis 75NT',
        className: `solis-75nt-img`,
        desc1: 'Namenjeni za korišćenje u poljoprivredi, komunalne radove i transport uz lakoću rada.',
        desc2: 'SOLIS N serija sa uskim razmakom između točkova, garantuje maksimalne performanse u primeni u voćarstvu i vinogradarstvu. Sinhronizovana transmisija kod ove serije obezbeđuje lakoću rada uz visoku produktivnost.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 75NT',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            '4100 ELT',
            'Tip motora',
            'Četvorotaktni turbo sa direktnim ubrzavanjem',
            'Kategorija (ks)',
            '75',
            'Snaga (kW)',
            '52',
            'Radna zapremina cc/ broj cilindara',
            '3707 / 4',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Sinhroni 12napred + 12 nazad',
            'Maksimalna brzina (km/h)',
            '31.1',
            'Tip kvačila',
            'Dvostruko',
            'Priključno vratilo ',
            'Nezavisno/sinhronizovano ( 540-750 o/min )',
            'Kočnice',
            'Diskovi u ulju',
            'Upravljač',
            'Hidraulični',
            'Sila dizanja hidraulike ( kg )',
            '2500',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 2 Jednosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '8 x 18 / 14.9 x 24',
            'Međuosovinsko rastojanje (mm)',
            '2216',
            'Dimenzije sa kabinom (DxŠxV-mm) ',
            '4150 x 1475 x 2310',
            'Težina bez kabine/sa kabinom (kg)',
            '2880/3120',
        ],

        standardnaOprema: 'Opis Proizvoda',
        standardLi: [
            ' - Keramička lamela',
            ' - Planetarni reduktori',
            ' - Sinhro menjač ( 12+12 brzina )',
            ' - Hidraulični sistem MITA ( Italija )',
            ' - Niska potrošnja goriva',
            ' - Opcija sa i bez kabine',
            ' - Pumpa visokog pritiska i dizne – BOSCH',
            ' - Transmisija i prednji most CARRARO ( Italija )',
        ],

    },
    {
        _id: '5',
        nameUrl: 'solis-90nt',
        productHeader: 'Solis 90NT',
        className: `solis-90nt-img`,
        desc1: 'Namenjeni za korišćenje u poljoprivredi, komunalne radove i transport uz lakoću rada.',
        desc2: 'SOLIS N serija sa uskim razmakom između točkova, garantuje maksimalne performanse u primeni u voćarstvu i vinogradarstvu. Sinhronizovana transmisija kod ove serije obezbeđuje lakoću rada uz visoku produktivnost.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 90NT',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            '4105 ELT',
            'Tip motora',
            'Četvorotaktni turbo sa direktnim ubrzavanjem',
            'Kategorija (ks)',
            '90',
            'Snaga (kW)',
            '62',
            'Radna zapremina cc/ broj cilindara',
            '3707 / 4',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Sinhroni 12napred + 12 nazad',
            'Maksimalna brzina (km/h)',
            '31.1',
            'Tip kvačila',
            'Dvostruko',
            'Priključno vratilo ',
            'Nezavisno/sinhronizovano ( 540-750 o/min )',
            'Kočnice',
            'Diskovi u ulju',
            'Upravljač',
            'Hidraulični',
            'Sila dizanja hidraulike ( kg )',
            '2500',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 2 Jednosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '8 x 18 / 14.9 x 24',
            'Međuosovinsko rastojanje (mm)',
            '2216',
            'Dimenzije sa kabinom (DxŠxV-mm) ',
            '4150 x 1475 x 2310',
            'Težina bez kabine/sa kabinom (kg)',
            '2886/3126',
        ],

        standardnaOprema: 'Opis Proizvoda',
        standardLi: [
            ' - Keramička lamela',
            ' - Planetarni reduktori',
            ' - Sinhro menjač ( 12+12 brzina )',
            ' - Hidraulični sistem MITA ( Italija )',
            ' - Niska potrošnja goriva',
            ' - Opcija sa i bez kabine',
            ' - Pumpa visokog pritiska i dizne – BOSCH',
            ' - Transmisija i prednji most CARRARO ( Italija )',
        ],

    },
    {
        _id: '6',
        nameUrl: 'solis-60',
        productHeader: 'Solis 60',
        className: `solis-60-img`,
        desc1: 'Solis 60 su univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.',
        desc2: 'Solis 60 su univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.Pripadaju seriji Worldtrac, koji dele istu konstrukciju i transmisiju, a razlikuju se po veličini pneumatika i različitim snagama i tipovima motora. U njih se ugrađuju snažni četvorocilindrični motori, sa ekonomičnom potrošnjom goriva i visokim obrtnim momentom.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 60',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            '4100 FL',
            'Tip motora',
            'Četvorotaktni sa direktnim ubrzavanjem',
            'Kategorija (ks)',
            '65',
            'Snaga (kW)',
            '44,2',
            'Radna zapremina cc/ broj cilindara',
            '3707/4',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Sinhroni 12napred + 12 nazad',
            'Maksimalna brzina (km/h)',
            '32.5',
            'Tip kvačila',
            'Dvostruko',
            'Priključno vratilo ',
            'Nezavisno/sinhronizovano ( 540-750 o/min )',
            'Kočnice',
            'Diskovi u ulju',
            'Upravljač',
            'Hidraulični',
            'Sila dizanja hidraulike ( kg )',
            '2500',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 2 Jednosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '9.50×24/16.9×28',
            'Međuosovinsko rastojanje (mm)',
            '2345',
            'Dimenzije sa kabinom (DxŠxV-mm) ',
            '4160x1980x2442	',
            'Težina bez kabine/sa kabinom (kg)',
            '2885/3160',
        ],


        standardnaOprema: 'Prednosti',
        standardLi: [
            ' - Garancija 3 godine ili 2000 radnih sati',
            ' - Homologovan u skladu sa evropskim normama',
            ' - Pumpa visokog pritiska i dizne BOSCH ',
            ' - Transmisija(menjač i prenos), zadnja i prednja osovina CARRARO (Italija)',
            ' - Sinhroni menjač(12+12 brzina)',
            ' - Keramička lamela',
            ' - Planetarni reduktori na zadnjoj osovini',
            ' - Kočnice-diskovi u ulju',
            ' - Snažan i pouzdan hidraulični sistem nosivosti 2500kg-MITA (Italija)',
            ' - Dve brzine priključnog vratila -540 i 540E(750) o/min',
            ' - Nezavisna spojnica(kvačilo) za izlazno vratilo',
            ' - Bogat paket standardne opreme(kompresor, liftomatic, poteznice, radio/cd u kabini, set alata , set rezervnih delova)',
            ' - Dva besplatna servisa ',
        ],

        // standardOprema2: 'Glavne karakteristike',
        // standardLi2: [
        //     'Suvi filter vazduha, sa senzorom začepljenosti',
        //     'Prednji tegovi sa opcijom prednje poteznice isporučuju se kao standardna oprema(nosač tegova od 72 kg i 8 tegova po 31kg)',
        //     'Par zadnjih tegova se isporučuje kao standardna oprema( 2 x 34kg)',
        //     'Sigurnosni ram sa rotacionim svetlom je standardna oprema za opciju traktora bez kabine',
        //     'Priključivanje u 3 tačke II kategorije',
        //     '2 dvosmerna i 2 jednosmerni priključaka za hidrauliku',
        //     'Planetarni prenos snage na zadnje točkove',
        //     'Kočnice-diskovi u ulju',
        //     'Podešavanje hidraulike:određivanje položaja, plivajući, zaključavanje za transportni položaj i liftomatic (pamti zadati položaj hidraulike u radu)',
        //     'Moderno dizajnirana i komforna kabina sa sistemom za grejanje(Hisarlar, Turska)',
        //     'Podešavanje volana po visini i dubini (opcija sa kabinom)',
        //     'Digitalni klima uređaj u kabini(opcija)',
        //     'Muzički sistem(CD,radio) je standardna oprema u kabini',
        // ]
    },
    {
        _id: '7',
        nameUrl: 'solis-75',
        productHeader: 'Solis 75',
        className: `solis-75-img`,
        desc1: 'Solis 75 su univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.',
        desc2: 'Solis 75 su univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.Pripadaju seriji Worldtrac, koji dele istu konstrukciju i transmisiju, a razlikuju se po veličini pneumatika i različitim snagama i tipovima motora. U njih se ugrađuju snažni četvorocilindrični motori, sa ekonomičnom potrošnjom goriva i visokim obrtnim momentom.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 75',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            '4100 FL',
            'Tip motora',
            'Četvorotaktni turbo sa direktnim ubrzavanjem',
            'Kategorija (ks)',
            '75',
            'Snaga (kW)',
            '52',
            'Radna zapremina cc/ broj cilindara',
            '3707/4',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Sinhroni 12napred + 12 nazad',
            'Maksimalna brzina (km/h)',
            '31.9',
            'Tip kvačila',
            'Dvostruko',
            'Priključno vratilo ',
            'Nezavisno/sinhronizovano ( 540-750 o/min )',
            'Kočnice',
            'Diskovi u ulju',
            'Upravljač',
            'Hidraulični',
            'Sila dizanja hidraulike ( kg )',
            '2500',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 2 Jednosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '11.2×24/16.9×30',
            'Međuosovinsko rastojanje (mm)',
            '2345',
            'Dimenzije sa kabinom (DxŠxV-mm) ',
            '4160x1980x2462	',
            'Težina bez kabine/sa kabinom (kg)',
            '3025/3300',
        ],


        standardnaOprema: 'Prednosti',
        standardLi: [
            ' - Garancija 3 godine ili 2000 radnih sati',
            ' - Homologovan u skladu sa evropskim normama',
            ' - Pumpa visokog pritiska i dizne BOSCH ',
            ' - Transmisija(menjač i prenos), zadnja i prednja osovina CARRARO (Italija)',
            ' - Sinhroni menjač(12+12 brzina)',
            ' - Keramička lamela',
            ' - Planetarni reduktori na zadnjoj osovini',
            ' - Kočnice-diskovi u ulju',
            ' - Snažan i pouzdan hidraulični sistem nosivosti 2500kg-MITA (Italija)',
            ' - Dve brzine priključnog vratila -540 i 540E(750) o/min',
            ' - Nezavisna spojnica(kvačilo) za izlazno vratilo',
            ' - Bogat paket standardne opreme(kompresor, liftomatic, poteznice, radio/cd u kabini, set alata , set rezervnih delova)',
            ' - Dva besplatna servisa ',
        ],

        // standardOprema2: 'Glavne karakteristike',
        // standardLi2: [
        //     'Suvi filter vazduha, sa senzorom začepljenosti',
        //     'Prednji tegovi sa opcijom prednje poteznice isporučuju se kao standardna oprema(nosač tegova od 72 kg i 8 tegova po 31kg)',
        //     'Par zadnjih tegova se isporučuje kao standardna oprema( 2 x 34kg)',
        //     'Sigurnosni ram sa rotacionim svetlom je standardna oprema za opciju traktora bez kabine',
        //     'Priključivanje u 3 tačke II kategorije',
        //     '2 dvosmerna i 2 jednosmerni priključaka za hidrauliku',
        //     'Planetarni prenos snage na zadnje točkove',
        //     'Kočnice-diskovi u ulju',
        //     'Podešavanje hidraulike:određivanje položaja, plivajući, zaključavanje za transportni položaj i liftomatic (pamti zadati položaj hidraulike u radu)',
        //     'Moderno dizajnirana i komforna kabina sa sistemom za grejanje(Hisarlar, Turska)',
        //     'Podešavanje volana po visini i dubini (opcija sa kabinom)',
        //     'Digitalni klima uređaj u kabini(opcija)',
        //     'Muzički sistem(CD,radio) je standardna oprema u kabini',
        // ]
    },
    {
        _id: '8',
        nameUrl: 'solis-90',
        productHeader: 'Solis 90',
        className: `solis-90-img`,
        desc1: 'Solis 90 su univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.',
        desc2: 'Solis 90 su univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.Pripadaju seriji Worldtrac, koji dele istu konstrukciju i transmisiju, a razlikuju se po veličini pneumatika i različitim snagama i tipovima motora. U njih se ugrađuju snažni četvorocilindrični motori, sa ekonomičnom potrošnjom goriva i visokim obrtnim momentom.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 90',
        table1: [
            'Pogon',
            '4 WD',
            'Model motora',
            '4105 ELT',
            'Tip motora',
            'Četvorotaktni turbo sa direktnim ubrzavanjem',
            'Kategorija (ks)',
            '90',
            'Snaga (kW)',
            '62',
            'Radna zapremina cc/ broj cilindara',
            '4087/4',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Menjač/broj stepeni prenosa',
            'Sinhroni 12napred + 12 nazad',
            'Maksimalna brzina (km/h)',
            '33.4',
            'Tip kvačila',
            'Dvostruko',
            'Priključno vratilo ',
            'Nezavisno/sinhronizovano ( 540-750 o/min )',
            'Kočnice',
            'Diskovi u ulju',
            'Upravljač',
            'Hidraulični',
            'Sila dizanja hidraulike ( kg )',
            '2500',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 2 Jednosmerna',
            'Dimenzije guma (prednje/zadnje)',
            '12.4×24/18.4×30',
            'Međuosovinsko rastojanje (mm)',
            '2515',
            'Dimenzije sa kabinom (DxŠxV-mm) ',
            '4160x1980x2487',
            'Težina bez kabine/sa kabinom (kg)',
            '3252/3527',
        ],


        standardnaOprema: 'Prednosti',
        standardLi: [
            ' - Garancija 3 godine ili 2000 radnih sati',
            ' - Homologovan u skladu sa evropskim normama',
            ' - Pumpa visokog pritiska i dizne BOSCH ',
            ' - Transmisija(menjač i prenos), zadnja i prednja osovina CARRARO (Italija)',
            ' - Sinhroni menjač(12+12 brzina)',
            ' - Keramička lamela',
            ' - Planetarni reduktori na zadnjoj osovini',
            ' - Kočnice-diskovi u ulju',
            ' - Snažan i pouzdan hidraulični sistem nosivosti 2500kg-MITA (Italija)',
            ' - Dve brzine priključnog vratila -540 i 540E(750) o/min',
            ' - Nezavisna spojnica(kvačilo) za izlazno vratilo',
            ' - Bogat paket standardne opreme(kompresor, liftomatic, poteznice, radio/cd u kabini, set alata , set rezervnih delova)',
            ' - Dva besplatna servisa ',
        ],

        // standardOprema2: 'Glavne karakteristike',
        // standardLi2: [
        //     'Suvi filter vazduha, sa senzorom začepljenosti',
        //     'Prednji tegovi sa opcijom prednje poteznice isporučuju se kao standardna oprema(nosač tegova od 72 kg i 8 tegova po 31kg)',
        //     'Par zadnjih tegova se isporučuje kao standardna oprema( 2 x 34kg)',
        //     'Sigurnosni ram sa rotacionim svetlom je standardna oprema za opciju traktora bez kabine',
        //     'Priključivanje u 3 tačke II kategorije',
        //     '2 dvosmerna i 2 jednosmerni priključaka za hidrauliku',
        //     'Planetarni prenos snage na zadnje točkove',
        //     'Kočnice-diskovi u ulju',
        //     'Podešavanje hidraulike:određivanje položaja, plivajući, zaključavanje za transportni položaj i liftomatic (pamti zadati položaj hidraulike u radu)',
        //     'Moderno dizajnirana i komforna kabina sa sistemom za grejanje(Hisarlar, Turska)',
        //     'Podešavanje volana po visini i dubini (opcija sa kabinom)',
        //     'Digitalni klima uređaj u kabini(opcija)',
        //     'Muzički sistem(CD,radio) je standardna oprema u kabini',
        // ]
    },
    {
        _id: '9',
        nameUrl: 'solis-50',
        productHeader: 'Solis 50',
        className: `solis-50-img`,
        desc1: 'Solis 50 u univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport.',
        desc2: 'Solis 50 u univerzalni traktori namenjeni za korišćenje u poljoprivredi, komunalne radove i transport. Opremljeni su proverenim i pouzdanim trocilindričim motorima sa ekonomičnom potrošnjom goriva i visokim obrtnim momentom. Snažna i masivna konstrukcija, veliko međuosovinsko rastojanje, keramička lamela, kočnice sa diskovima u ulju, kao i opcija pogona na sve točkove omogućavaju korišćenje i u najtežim radnim uslovima. U ponudi su modeli sa pogonom na 2 ili 4točka, sa ili bez kabine.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Solis 50',
        table1: [
            'Pogon',
            '2 WD , 4WD',
            'Model motora',
            '3102 EL',
            'Tip motora',
            'četvorotaktni sa direktnim ubrizgavanjem',
            'Kategorija (ks)',
            '50',
            'Snaga (kW)',
            '35',
            'Radna brzina (cc)/broj cilindara',
            '2893',
            'Sistem za hlađenje',
            'Vodeno pod pritiskom',
            'Broj cilindara',
            '3',
            'Prečnik cilindra/hod klipa (mm)',
            '102/118',
            'Nominalni broj obrtaja (o/min)',
            '2100',
            'Maksimalni obrtni moment (Nm) ',
            '190',
            'Filter vazduha',
            'Suvi,sa senzorom začepljenosti',
            'Pumpa za ubrizgavanje goriva / dizne',
            'BOSCH / BOSCH',
            'Radni pritisak ulja (bar)',
            '2.1 – 4.5',
            'Kompresioni odnos',
            '18:4:1',
            'Grejač(hladan start)/tip',
            'DA,grejač na usisnoj grani',
            'Tip Menjača',
            'Mehanički (klizni)',
            'Broj stepeni prenosa',
            '8N+2R',
            'Odnos stepena prenosa i brzine (km/h) - napred',
            'S I-1.77; S II-2.58; S III-4.34; S IV-7.26 | B I-7.56; B II-10.99; B III18.49; B IV-30.92',
            'Odnos stepena prenosa i brzine (km/h) - nazad',
            'S I-2.27, B I-9.68',
            'Maksimalna brzina (km/h)',
            '33.9',
            'Blokada diferencijala',
            'Da,nogom',
            'Tip Kvačila',
            'Dvostepeno',
            'Vrsta lamele - pogonska / priključno vratilo',
            'Keramička(4 kraka) / azbestna',
            'Tip Priključnog vratila',
            'Nezavisno/azbestna',
            'Broj obrtaja(o/min)',
            '540',
            'Broj žljebova',
            '6',
            'Maksimalna snaga(KS)',
            '41',
            'Tip Kočnica',
            'Diskovi u ulju',
            'Broj kočionih diskova',
            '4',
            'Parkirna kočnica',
            'Da,nezavisna',
            'Kocnica za prikolicu',
            'Da,nezavisna',
            'Tip Upravljača',
            'Hidraulički',
            'Radijus zakretanja(m)',
            '3,7',
            'Hidraulični sistem - sila dizanja(kg)',
            '1600',
            'Tip pumpe',
            'Zupčasta(Sonalika)',
            'Kapacite pumpe (I/min)',
            '25',
            'Opcije podešavanja',
            'Položaja i opterećivanja(plivajući)',
            'Kačenje u tri tačke',
            'Kategorija II',
            'Izvod za hidrauliku',
            '2 Dvosmerna / 1 Jednosmerna',
            'Akumulator',
            '12V,88A',
            'Elektrostarter(Alnaser)',
            '12V,2.7KW',
            'Sirena',
            'DA',
            'Sedmopolni priključak',
            'DA',
            'Kutija sa osiguračima',
            'DA',
            'Sigurnosni prekidač menjača',
            'DA',
            'Sigurnosni prekidač kvačila',
            'DA',
            'Svetla',
            'Prednji farovi, pozicije sa migavcima, sva četiri migavca, zadnja( stop, migavci, pozicije),radna svetla, za registarsku tablicu.',
            'Instrument tabla',
            'Merač (broja obrtaja motora-časova rada), merač temperature rashladne tečnosti, voltmetar, merač pritiska ulja u motoru, merač goriva u rezervoaru, migavci levi/desni, pokazivač pogona 2WD/4WD, indikator punjenja akumulatora, migavci na prikolici, indikator začepljenosti filtera za vazduh, duga svetla .',
            'Prednje Gume',
            '6.00×16',
            'Zadnje Gume',
            '13.6×28',
            'Pritisak-prednje(bar)',
            '2.5',
            'Pritisak-zadnje(bar)',
            ' 1.1 za njivu | 1.5 za put',
            'Međuosovinsko rastojanje(mm)',
            '1980',
            'Ukupna dužina(mm)',
            '3820',
            'Ukupna širina(mm)',
            '1790',
            'Visina sa sigurnosnim ramom(mm)',
            '2450',
            'Visina sa kabinom(mm)',
            '2580',
            'Prednja osovina(mm)',
            '441',
            'Izmedju osovina(mm)',
            '315',
            'Zadnja osovina(mm)',
            '536',
            'Širina traga prednjih točkova(mm)',
            '1310',
            'Širina traga zadnjih točkova(mm)',
            '1420',
            'Težina traktora sa standardnim tegovima-bez kabine /sa kabinom(kg)',
            '2445 / 2710',
            'Rezervoar za gorivo (lit)-bez kabine/sa kabinom',
            '55',
            'Rashladna tečnost u motoru (lit)',
            '11',
            'Ulje u motoru (lit)',
            '8.2',
            'Ulje u transmisiji(menjac,diferencijal i hidraulika) (lit)',
            '55',
            'Ulje u servo upravljaču (lit)',
            '2.5',
            'Ulje u prednjem mostu (lit)',
            'NE',
            'Ulje u reduktoru prednje osovine (lit)',
            'NE',
            'Sigurnosni ram',
            'DA',
            'Topling',
            'DA',
            'Set rezervnih delova',
            'DA',
            'Set alata',
            'DA',
            'Retrovizori-levi/desni',
            'DA,sa obe strane',
            'Horizontalni auspuh',
            'DA',
            'Tegovi-prednji/zadnji(kg)',
            'DA,napred 4X10',
            'Rotaciono svetlo',
            'DA',
        ],


        standardnaOprema: 'Prednosti',
        standardLi: [
            ' - Garancija 3 godine ili 2000 radnih sati',
            ' - Homologovan u skladu sa evropskim normama',
            ' - Pumpa visokog pritiska i dizne BOSCH',
            ' - Prednja osovina CARRARO(Italija) -za 4wd',
            ' - Keramička lamela',
            ' - Kočnice-diskovi u ulju',
            ' - Servo upravljač',
            ' - Bogat paket standardne opreme(kompresor, liftomatic, poteznice, radio/cd u kabini, set alata , set rezervnih delova)',
            ' - Dva besplatna servisa',
        ],
    },
]

export const both = [...Solis];
export { Solis }