const Carraro = [
    {
        _id: '1',
        nameUrl: 'agricube-frutteto-80f',
        productHeader: 'Agricube Frutteto 80f',
        className: `agricube-frutteto-80-img`,
        desc1: 'Traktor vocar veliki. Voćar je proučavan o svakom detalju kako bi pojednostavio rad a ujedno pružio ugodnu vožnju.',
        desc2: 'Frutteto (Voćar) – Voćar je proučavan o svakom detalju kako bi pojednostavio rad a ujedno pružio ugodnu vožnju . Jednostavne i dinamičke linije, uz svoju kompaktnost , odgovara zahtevima onih koji rade u specijalizovanim zasadima, u kombinacijama sa FTP motorima od 75, 88 i 100 KS .',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Frutteto 80f',

        left1Title: 'Motor, Električni sistem, Menjač',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo',
            'Sistem hlađenja',
            'A vodeno',
            'Max snaga ISO kW/ks',
            '55 / 74,8',
            'Snaga ISO na vratilu kW/ks',
            '46 / 62',
            'Obrtaji za max snagu',
            '2.300',
            'Obr.za max o moment',
            '1.250',
            'Obrtni moment max',
            '310 Nm@1.250rpm',
            'Rezerva obrt.mom.',
            '37 %',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Kapacitet pomoćnog rezervoara',
            '19 l',
            'Auspuh',
            'Horizontalni',
            'Kapacitet rezervoara kad je sa podiznim rukama',
            '50 l',
            'Akumulator',
            '100 Ah',
            'Alternator',
            '80 A',
            'Pokretni motor',
            '4,2 kW',
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '1,5 km/h sa točkovima pozadi 14.9R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 14.9R28',
        ],




        left2Title: 'Kardansko vratilo, Eleketro hidraulično kard.vratilo',
        table2: [
            'Brzina ( disk lamela suva )',
            '540 – 540 / 540 E – 540 / 1.000',
            'Sinhro kardansko vratilo',
            'Opciono',
            'Pokazivač brzine na tabli',
            'Osnovno',
            'Brzina ( disk lamela suva )',
            '540 / 540 E – 540 / 1.000',
            'Kardansko vrat. sinhro',
            'Osnovno',
            'Pokazivač brzine na instrument tabli',
            'Osnovno',
        ],


        left3Title: 'Kvačilo, Kočnice',
        table3: [
            'Nezavisno, suvo',
            '11”',
            'Kočnice, potezne',
            'Mehaničko i hidraulično integrisano',
            'Konfiguracija kočnica',
            'Diskovi u ulju',
        ],




        left4Title: 'Blokada difernecijala, Prednji most, Zadnji most',
        table4: [
            'Tip',
            'Mehaničko',
            'Uključenje',
            'Elektrohidraulično',
            'Maksimalni ugao zaokretanja',
            '55 ⁰',
            'Ugao oscilacija',
            '8 ⁰',
            'Razmak između prirubnice',
            '990 mm',
            'Uključenje 4 WD',
            'Elektrohidraulično',
            'Diferencijal',
            'Proklizavanje ograničeno',
            'Tip',
            'Trkači',
            'Odnos',
            '6:1',
            'Razdaljina prirubnica',
            '990 mm',
            'Uključenje 4 WD',
            '972 mm',
        ],


        left5Title: 'Hidraulični sistem, Kačenje tri tačke, Kuka za vuču',
        table5: [
            'Kapacitet pumpe ( lit/min )',
            'Sa 2 pumpe ( osnovno ): 61,2 + 24,8',
            'Kapacitet pumpe ( lit/min )',
            'Sa 3 pumpe ( opciono ): 41,5+35+24,8',
            'Razvodnik',
            '1 SE+1 DE 3 Pos / 1 SE + 1 DE 4 Pos sa neutralnim jednostavnim povraćajem ( 4 izlaza pozadi ), kontrola protoka za istovremenu upotrebu razvodnika i podizanja',
            'Maksimalni kapacitet podizanja',
            '2.600 kg  ( osnovno ) – 3.000 kg ( opciono )',
            'Podizanje',
            'Mehaničko sa položajem, oslanjanje i kontrolom mešanja ( osnovno ) – Električno ( opcija )',
            'Kačenje',
            '1 / 1N / 2 kat.',
            'Donje poluge',
            'Sa okcem, fiksne, Kat.2 | Sa okcem, štelujuća, Kat.1/1N/2 | Brzo kačenje, štelujuća, Kat. 2/1/1N',
            'Klinovi / Štelujuća',
            'Kategorija Cuna C ( osnovno ) | Kategorija Cuna C + D2 ( opcija )',
        ],



        left6Title: 'Prednji tegovi',
        table6: [
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
            'Traktor – Varijanta',
            'Sa zaštitnim ramom | Sa kabinom',

        ],

        left7Title: 'Sa zaštitnim ramom',
        table7: [
            'Zaštitni ram',
            'Obarajući napred',
            'Volan',
            'Fiksni',
            'Sedište',
            'Mehaničko, Pvc',
            'Retrovizor',
            '1 retrovizor teleskopski sa leve strane SX ( osnovno ) | 1 retrovizor teleskopski sa desne strane DX ( opciono )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Visina sa podignutim ramom',
            '2.533 mm',
            'Težina traktora sa ramom',
            '2.730 kg',

        ],

        left8Title: 'Sa kabinom',
        table8: [
            'Kabina',
            'Nezavisna, zvučna izolacija na 4 tiha bloka sa ventilacijom i grejanjem ( osnovno ) | Klima ( opcija )',
            'Volan',
            'Fiksni ( osnovno ) | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno sa platnom ( osnovno ) | Nezavisno, pneumatsko sa platnom ( opcija )',
            'Retrovizor',
            'Dva retrovizora sa obe strane ( osnovno ) | 1 unutrašnje ogledalo ( opcija )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu',
            'Srpski jezik',
        ],

        left9Title: 'Dimenzije traktora sa kabinom',
        table9: [
            'Ukupna dužina traktora bez tegova',
            '3.991 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.316 mm',
            'Ukupna visina traktora sa kabinom',
            '2.385 mm',
            'Max širina traktora',
            '1.980 mm',
            'Prednji klirens',
            '295 mm',
            'Zadnji klirens',
            '355 mm',
            'Širina prednjeg traga',
            '9.97 / 1.625 mm',
            'Širina zadnjeg traga',
            '1.102 / 1.646 mm',
            'Težina traktora sa kabinom',
            '2.965 kg',
        ],

        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '2',
        nameUrl: 'agricube-frutteto-90f',
        productHeader: 'Agricube Frutteto 90f',
        className: `agricube-frutteto-90-img`,
        desc1: 'Traktor vocar veliki. Voćar je proučavan o svakom detalju kako bi pojednostavio rad a ujedno pružio ugodnu vožnju.',
        desc2: 'Frutteto (Voćar) – Voćar je proučavan o svakom detalju kako bi pojednostavio rad a ujedno pružio ugodnu vožnju . Jednostavne i dinamičke linije, uz svoju kompaktnost , odgovara zahtevima onih koji rade u specijalizovanim zasadima, u kombinacijama sa FTP motorima od 75, 88 i 100 KS .',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Frutteto 90f',

        left1Title: 'Motor, Električni sistem, Menjač',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo intercooler',
            'Sistem hlađenja',
            'A vodeno',
            'Max snaga ISO kW/ks',
            '65 / 88,4',
            'Snaga ISO na vratilu kW/ks',
            '55 / 75',
            'Obrtaji za max snagu',
            '2.300',
            'Obr.za max o moment',
            '1.300',
            'Obrtni moment max',
            '350 Nm@1.300rpm',
            'Rezerva obrt.mom.',
            '36 %',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Kapacitet pomoćnog rezervoara',
            '19 l',
            'Auspuh',
            'Horizontalni',
            'Kapacitet rezervoara kad je sa podiznim rukama',
            '50 l',
            'Akumulator',
            '100 Ah',
            'Alternator',
            '80 A',
            'Pokretni motor',
            '4,2 kW',
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '1,5 km/h sa točkovima pozadi 6.9R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 14.9R28',
        ],



        left2Title: 'Kardansko vratilo, Eleketro hidraulično kard.vratilo',
        table2: [
            'Brzina ( disk lamela suva )',
            '540 – 540 / 540 E – 540 / 1.000',
            'Sinhro kardansko vratilo',
            'Opciono',
            'Pokazivač brzine na tabli',
            'Osnovno',
            'Brzina ( disk lamela suva )',
            '540 / 540 E – 540 / 1.000',
            'Kardansko vrat. sinhro',
            'Osnovno',
            'Pokazivač brzine na instrument tabli',
            'Osnovno',
        ],


        left3Title: 'Kvačilo, Kočnice',
        table3: [
            'Nezavisno, suvo',
            '11”',
            'Kočnice, potezne',
            'Mehaničko i hidraulično integrisano',
            'Konfiguracija kočnica',
            'Diskovi u ulju',
        ],



        left4Title: 'Blokada difernecijala, Prednji most, Zadnji most',
        table4: [
            'Tip',
            'Mehaničko',
            'Uključenje',
            'Elektrohidraulično',
            'Maksimalni ugao zaokretanja',
            '55 ⁰',
            'Ugao oscilacija',
            '8 ⁰',
            'Razmak između prirubnice',
            '990 mm',
            'Uključenje 4 WD',
            'Elektrohidraulično',
            'Diferencijal',
            'Proklizavanje ograničeno',
            'Tip',
            'Trkači',
            'Odnos',
            '6:1',
            'Razdaljina prirubnica',
            '990 mm',
            'Uključenje 4 WD',
            '972 mm',
        ],




        left5Title: 'Hidraulični sistem, Kačenje tri tačke, Kuka za vuču',
        table5: [
            'Kapacitet pumpe ( lit/min )',
            'Sa 2 pumpe ( osnovno ): 61,2 + 24,8',
            'Kapacitet pumpe ( lit/min )',
            'Sa 3 pumpe ( opciono ): 41,5+35+24,8',
            'Razvodnik',
            '1 SE+1 DE 3 Pos / 1 SE + 1 DE 4 Pos sa neutralnim jednostavnim povraćajem ( 4 izlaza pozadi ), kontrola protoka za istovremenu upotrebu razvodnika i podizanja',
            'Maksimalni kapacitet podizanja',
            '2.600 kg  ( osnovno ) – 3.000 kg ( opciono )',
            'Podizanje',
            'Mehaničko sa položajem, oslanjanje i kontrolom mešanja ( osnovno ) – Električno ( opcija )',
            'Kačenje',
            '1 / 1N / 2 kat.',
            'Donje poluge',
            'Sa okcem, fiksne, Kat.2 | Sa okcem, štelujuća, Kat.1/1N/2 | Brzo kačenje, štelujuća, Kat. 2/1/1N',
            'Klinovi / Štelujuća',
            'Kategorija Cuna C ( osnovno ) | Kategorija Cuna C + D2 ( opcija )',
        ],


        left6Title: 'Prednji tegovi',
        table6: [
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
            'Traktor – Varijanta',
            'Sa zaštitnim ramom | Sa kabinom',

        ],

        left7Title: 'Sa zaštitnim ramom',
        table7: [
            'Zaštitni ram',
            'Obarajući napred',
            'Volan',
            'Fiksni',
            'Sedište',
            'Mehaničko, Pvc',
            'Retrovizor',
            '1 retrovizor teleskopski sa leve strane SX ( osnovno ) | 1 retrovizor teleskopski sa desne strane DX ( opciono )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Visina sa podignutim ramom',
            '2.533 mm',
            'Težina traktora sa ramom',
            '2.730 kg',

        ],

        left8Title: 'Sa kabinom',
        table8: [
            'Kabina',
            'Nezavisna, zvučna izolacija na 4 tiha bloka sa ventilacijom i grejanjem ( osnovno ) | Klima ( opcija )',
            'Volan',
            'Fiksni ( osnovno ) | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno sa platnom ( osnovno ) | Nezavisno, pneumatsko sa platnom ( opcija )',
            'Retrovizor',
            'Dva retrovizora sa obe strane ( osnovno ) | 1 unutrašnje ogledalo ( opcija )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu',
            'Srpski jezik',
        ],

        left9Title: 'Dimenzije traktora sa kabinom',
        table9: [
            'Ukupna dužina traktora bez tegova',
            '3.991 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.316 mm',
            'Ukupna visina traktora sa kabinom',
            '2.385 mm',
            'Max širina traktora',
            '1.980 mm',
            'Prednji klirens',
            '295 mm',
            'Zadnji klirens',
            '355 mm',
            'Širina prednjeg traga',
            '9.97 / 1.625 mm',
            'Širina zadnjeg traga',
            '1.102 / 1.646 mm',
            'Težina traktora sa kabinom',
            '2.965 kg',
        ],

        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '3',
        nameUrl: 'agricube-frutteto-100f',
        productHeader: 'Agricube Frutteto 100f',
        className: `agricube-frutteto-100-img`,
        desc1: 'Traktor vocar veliki. Voćar je proučavan o svakom detalju kako bi pojednostavio rad a ujedno pružio ugodnu vožnju.',
        desc2: 'Frutteto (Voćar) – Voćar je proučavan o svakom detalju kako bi pojednostavio rad a ujedno pružio ugodnu vožnju . Jednostavne i dinamičke linije, uz svoju kompaktnost , odgovara zahtevima onih koji rade u specijalizovanim zasadima, u kombinacijama sa FTP motorima od 75, 88 i 100 KS .',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Frutteto 100f',

        left1Title: 'Motor, Električni sistem, Menjač',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '4.500 c³',
            'Broj cilind/konfigur.',
            '4, turbo intercooler',
            'Sistem hlađenja',
            'A vodeno',
            'Max snaga ISO kW/ks',
            '74 / 100,6',
            'Snaga ISO na vratilu kW/ks',
            '63 / 86',
            'Obrtaji za max snagu',
            '2.200',
            'Obr.za max o moment',
            '1.250',
            'Obrtni moment max',
            '430 Nm@1.250rpm',
            'Rezerva obrt.mom.',
            '28 %',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Kapacitet pomoćnog rezervoara',
            '19 l',
            'Auspuh',
            'Horizontalni',
            'Kapacitet rezervoara kad je sa podiznim rukama',
            '50 l',
            'Akumulator',
            '100 Ah',
            'Alternator',
            '90 A',
            'Pokretni motor',
            '4,2 kW',
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '1,5 km/h sa točkovima pozadi 14.9R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 14.9R28',
        ],

        left2Title: 'Kardansko vratilo, Eleketro hidraulično kard.vratilo',
        table2: [
            'Brzina ( disk lamela suva )',
            '540 – 540 / 540 E – 540 / 1.000',
            'Sinhro kardansko vratilo',
            'Opciono',
            'Pokazivač brzine na tabli',
            'Osnovno',
            'Brzina ( disk lamela suva )',
            '540 / 540 E – 540 / 1.000',
            'Kardansko vrat. sinhro',
            'Osnovno',
            'Pokazivač brzine na instrument tabli',
            'Osnovno',
        ],


        left3Title: 'Kvačilo, Kočnice',
        table3: [
            'Nezavisno, suvo',
            '11”',
            'Kočnice, potezne',
            'Mehaničko i hidraulično integrisano',
            'Konfiguracija kočnica',
            'Diskovi u ulju',
        ],



        left4Title: 'Blokada difernecijala, Prednji most, Zadnji most',
        table4: [
            'Tip',
            'Mehaničko',
            'Uključenje',
            'Elektrohidraulično',
            'Maksimalni ugao zaokretanja',
            '55 ⁰',
            'Ugao oscilacija',
            '8 ⁰',
            'Razmak između prirubnice',
            '990 mm',
            'Uključenje 4 WD',
            'Elektrohidraulično',
            'Diferencijal',
            'Proklizavanje ograničeno',
            'Tip',
            'Trkači',
            'Odnos',
            '6:1',
            'Razdaljina prirubnica',
            '990 mm',
            'Uključenje 4 WD',
            '972 mm',
        ],


        left5Title: 'Hidraulični sistem, Kačenje tri tačke, Kuka za vuču',
        table5: [
            'Kapacitet pumpe ( lit/min )',
            'Sa 2 pumpe ( osnovno ): 61,2 + 24,8',
            'Kapacitet pumpe ( lit/min )',
            'Sa 3 pumpe ( opciono ): 41,5+35+24,8',
            'Razvodnik',
            '1 SE+1 DE 3 Pos / 1 SE + 1 DE 4 Pos sa neutralnim jednostavnim povraćajem ( 4 izlaza pozadi ), kontrola protoka za istovremenu upotrebu razvodnika i podizanja',
            'Maksimalni kapacitet podizanja',
            '2.600 kg  ( osnovno ) – 3.000 kg ( opciono )',
            'Podizanje',
            'Mehaničko sa položajem, oslanjanje i kontrolom mešanja ( osnovno ) – Električno ( opcija )',
            'Kačenje',
            '1 / 1N / 2 kat.',
            'Donje poluge',
            'Sa okcem, fiksne, Kat.2 | Sa okcem, štelujuća, Kat.1/1N/2 | Brzo kačenje, štelujuća, Kat. 2/1/1N',
            'Klinovi / Štelujuća',
            'Kategorija Cuna C ( osnovno ) | Kategorija Cuna C + D2 ( opcija )',
        ],


        left6Title: 'Prednji tegovi',
        table6: [
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
            'Traktor – Varijanta',
            'Sa zaštitnim ramom | Sa kabinom',

        ],

        left7Title: 'Sa zaštitnim ramom',
        table7: [
            'Zaštitni ram',
            'Obarajući napred',
            'Volan',
            'Fiksni',
            'Sedište',
            'Mehaničko, Pvc',
            'Retrovizor',
            '1 retrovizor teleskopski sa leve strane SX ( osnovno ) | 1 retrovizor teleskopski sa desne strane DX ( opciono )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Visina sa podignutim ramom',
            '2.533 mm',
            'Težina traktora sa ramom',
            '2.730 kg',

        ],

        left8Title: 'Sa kabinom',
        table8: [
            'Kabina',
            'Nezavisna, zvučna izolacija na 4 tiha bloka sa ventilacijom i grejanjem ( osnovno ) | Klima ( opcija )',
            'Volan',
            'Fiksni ( osnovno ) | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno sa platnom ( osnovno ) | Nezavisno, pneumatsko sa platnom ( opcija )',
            'Retrovizor',
            'Dva retrovizora sa obe strane ( osnovno ) | 1 unutrašnje ogledalo ( opcija )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu',
            'Srpski jezik',
        ],

        left9Title: 'Dimenzije traktora sa kabinom',
        table9: [
            'Ukupna dužina traktora bez tegova',
            '3.991 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.316 mm',
            'Ukupna visina traktora sa kabinom',
            '2.385 mm',
            'Max širina traktora',
            '1.980 mm',
            'Prednji klirens',
            '295 mm',
            'Zadnji klirens',
            '355 mm',
            'Širina prednjeg traga',
            '9.97 / 1.625 mm',
            'Širina zadnjeg traga',
            '1.102 / 1.646 mm',
            'Težina traktora sa kabinom',
            '2.965 kg',
        ],

        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '4',
        nameUrl: 'carraro-v75',
        productHeader: 'Agricube Frutteto V75',
        className: `carraro-v75-img`,
        desc1: 'Kompaktnost i širok izbor konfiguracije, udobnost,  po savremenim ergonomskim rešenjima. Pouzdanost za vinograde.',
        desc2: 'Elegantnog dizajna, sa motorima FPT, stvorena da objedini osobine Performansa, Kvaliteta i Pouzdanosti  za  vinogradarske  potrebe. Kompaktnost i širok izbor konfiguracije, udobnost,  po savremenim ergonomskim rešenjima, cine da Carraro bude idealan traktor za sve radove u specijalizovanim  sektorima.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Carraro V75',


        left1Title: 'Model v75',
        table1: [
            'Maksimalna snaga kW / ks',
            '55/74,8',
            'Broj obrtaja ',
            '2.300',
            'Obrtni moment Nm',
            '309',
        ],


        left2Title: 'Motor',
        table2: [
            'Motor',
            'FTP – F34 ( STAGE 3B ) – 3.400 cm³',
            'Kapacitet rezervoara',
            '745 l',
            'Auspuh',
            'Horizontalni',
            'Broj cilindara',
            '4 – turbo intercooler – 2 ventila po cilindru',
            'Sistem hlađenja',
            'A vodeno',
        ],


        left3Title: 'Menjač, Brzina',
        table3: [
            'Transmisija',
            '24+24, 0.5-40 km/h , mehanički reverzer, mehanički HI-LO(sporo-brzo)',
            'Kočnica',
            'Mehanička i hidraulična, 10 lamele potopljene u ulju',
            'PTO ',
            '540/540E sinhro',
        ],


        left4Title: 'Maksimalna podizna moć, Kačenje',
        table4: [
            'Maksimalna podizna moć',
            '2600 kg',
            'Kačenje',
            'Podizne poluge štelujuće sa brzim kačenjem (CAT.2/1/1N)',
        ],

        left5Title: 'Podizači , Vučna kuka',
        table5: [
            'Podizači',
            'Mehanički',
            'Vučna kuka (sa klinom)',
            'Kačenje sa rupama .Kuka Cuna C',
        ],

        left6Title: 'Prednji točkovi, Zadnji točkovi',
        table6: [
            'Prednji točkovi',
            '6.50-16MI',
            'Zadnji točkovi',
            '280/85R28MI',

        ],


        left7Title: 'Dimenzije',
        table7: [
            'Ukupna dužina (mm)',
            '3.950',
            'Širina max i min (mm)',
            '1.462 / 1.181',
        ],


        left8Title: 'Kabina',
        table8: [
            'Visina sa kabinom (mm)',
            '2.390',
        ],

        left9Title: 'Rastojanje i Težina',
        table9: [
            'Međuosovinsko rastojanje (mm)',
            '2.148',
            'Težina traktora (kg)',
            '2.880',
        ],



        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '5',
        nameUrl: 'agricube-vigneto-80v',
        productHeader: 'Agricube Vigneto – 80V',
        className: `agricube-vigneto-80-img`,
        desc1: 'Agricube Vinogradar odgovara zahtevima rada na uskom prostoru ali bez gubitka konforta. Dostupan u verzijama sa kabinom.',
        desc2: 'Agricube Vigneto – traktor vinogradar – dostupan u verzijama sa kabinom ili rol barom,  sa svojim kompaktnim dimenzijama i ergonomičnom linijom, Agricube Vinogradar odgovara zahtevima rada na uskom prostoru ali bez gubitka konforta. Agricube Vinogradar je dostupan sa modelom 80V, sa motorom performansi FPT F5C, 4 cilindra, turbo od 75 KS.',
        teh_kar: 'Tehničke Karakteristike',

        left1Title: 'Motor, Električni sistem, Menjač',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C ( EURO IIIA )',
            'Kubika',
            '3.200 c³',
            'Broj cilindara / Konfiguracija',
            ' 4/turbo',
            'Sistem hlađenja',
            'vodeno',
            'Maksimalna snaga ISO kW/KS',
            '55 / 74,8',
            'Snaga na izlaznom vratilu kW/KS',
            '46 / 62',
            'Obrtaji pri max. snazi',
            '2.300',
            'Obrtaji pri max obrt, m.',
            '1.250',
            'Obrtni moment',
            '310 Nm/1.250 rpm',
            'Rezerva  obr.mom.',
            '37 %',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Kapacitet rezervoara sa prednjim kačenjem',
            '50 l',
            'Kapacitet pomoćnog rezervoara ( opciono )',
            '19 l',
            'Auspuh',
            'Horizontalan',
            'Akumulator',
            '100 Ah',
            'Alternator',
            '80 A',
            'Motor za start',
            '4,2 kW',
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Gama',
            '3 gama brzine Sporo/Srednje/Brzo – inverz. mehanički',
            'Minimalna brzina traktora',
            '1,4 km/h sa točkovima pozadi 13.6R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 13.6R28',
        ],



        left2Title: 'Uklj.kard.vrat.mehaničko',
        table2: [
            'Brzina ( disk lamele, suv )',
            '540 – 540 / 540 E – 540 / 1.000',
            'Kardansko vratilo – sinhro',
            'Opcija',
            'Pokazivač brzine kardanskog vartila',
            'Base',
        ],


        left3Title: 'Kvačilo, Kočnice',
        table3: [
            'Nezavisno, suvo',
            '11 ″',
            'Kočnice, potezne',
            'mehaničke i hidraulične integrisane',
            'Konfiguracija kočnica',
            'Diskovi u ulju',
        ],



        left4Title: 'Blokada zadnjeg diferencijala, Prednji most, Zadnji most',
        table4: [
            'Tip',
            'Mehaničko',
            'Uključenje',
            'Elektro hidraulično',
            'Maksimalni ugao zaokretanja',
            '55 º',
            'Ugao odstupanja',
            '8 º',
            'Razmak flanše',
            '925 mm',
            'Uključenje 4 WD',
            'Elektrohidraulično',
            'Diferencial',
            'Proklizavanje ograničeno',
            'Tip',
            'Planetarni',
            'Raport – odnos',
            '6:1',
            'Razmak flanše',
            '892 mm',
        ],


        left5Title: 'Hidraulični sistem',
        table5: [
            'Kapacitet pumpe l/min sa 2 pumpe (base)',
            '61,2+24,9',
            'Kapacitet pumpe l/min sa 3 pumpe (base)',
            '41,5+35+24,9',
            'Distibuteri',
            ' 1 SE+1 DE 3 Pos/1 SE+1 DE 4 Pos | Sa povraćajem jednostavnim ( 4 izlaza nazad ), sa nezavisnim protokom',
        ],


        left6Title: 'Kačenje u tri tačke',
        table6: [
            'Maksimalna podizna moć',
            '2.600 kg',
            'Tegovi prednji',
            '4 elemenata x 30 kg ( 120 kg ) – OPCIONO',
        ],


        left7Title: 'Sa platformom',
        table7: [
            'Platforma',
            'Nezavisna, na 4 silent block sa zvučnom izolacijom',
            'Zaštitni ram',
            'Sklapajući napred',
            'Volan',
            'Fiksni ( baze ), teleskopski i pod uglom ( opciono )',
            'Sedište',
            'Nezavisno, mehaničko. Pvc (baze)',
            'Retrovizor',
            '1 retrovizor teleskopski sa leve strane SX (baze) | 1 retrovizor teleskopski sa desne strane DX (opciono)',
            'Instrument tabla',
            'Multifunkcionalna',
            'Upustvo za upotrebu',
            'Srpski jezik',
        ],

        left8Title: 'Sa kabinom',
        table8: [
            'Kabina',
            'Zvučna izolacija, nezavisna, 4 silent block, ventilacija i grejanje | Klima ( opciono )',
            'Volan',
            'Fiksni ( baze ), teleskopski i ugaono pomeranje ( opciono )',
            'Sedište',
            'Nezavisno, mehaničko sa platnom ( baze ) – nezavisno | pneumatsko, platno  ( opciono )',
            'Retrovizori',
            'Dva retrovizora sa obe strane DX i SX – 1 ogledalo unutra ( opciono )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Upustvo za upotrebu',
            'Srpski jezik',
        ],

        left9Title: 'Kard.vrat.elektro hidr.',
        table9: [
            'Brzina ( disk lamela, suv )',
            '540/540 E – 540/1.000',
            'Kard. vrat. sinhro',
            'Baze',
            'Pokazivač brzine kard vratila',
            'Baze',
        ],

        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '6',
        nameUrl: 'agricube-frutteto-basso-80fb',
        productHeader: 'Frutteto Basso – 80FB',
        className: `agricube-frutteto-basso-80fb-img`,
        desc1: 'Nizak centar gravitacije i niskog profila čine ga pogodnim za upotrebu u brdovitim i planinskim terenima.',
        desc2: 'Frutteto Largo (Voćar Široki) – svestran , robustan i visokih performansi su pridevi koji najbolje opisuju ovaj novi model , namenjen za upotrebu u rasponu od otvorenih polja do voćnjaka . Nizak centar gravitacije i niskog profila čine ga pogodnim za upotrebu u brdovitim i planinskim terenima , obezbeđujući veću stabilnost od tradicionalnih specijalnih tegljača .',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Frutteto Basso 80FB',

        left1Title: 'Motor, Električni sistem',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo',
            'Sistem hlađenja',
            'Vodeno hlađenje ',
            'Max snaga ISO kW/ks',
            '55 / 74,8',
            'Snaga ISO na vratilu kW/ks',
            '46 / 62',
            'Obrtaji za max snagu',
            '2.300',
            'Obr.za max o moment',
            '1.250',
            'Obrtni moment max',
            '310 Nm@1.250rpm',
            'Rezerva obrt.mom.',
            '37 %',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Kapacitet rezervoara goriva sa prednjim PTO',
            '52,3 l',
            'Auspuh',
            'Horizontalni',
            'Akumulator',
            '100 Ah',
            'Alternator',
            '80 A',
            'Pokretni motor',
            '4,2 kW'
        ],


        left2Title: 'Menjač',
        table2: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '3 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '0,5 km/h sa 24” zadnja guma',
            'Maksimalna brzina traktora',
            '42 km/h sa 24” zadnja guma',
        ],


        left3Title: 'Mehanička snaga zatvorena servo kontrolom',
        table3: [
            'Brzina ( disk lamela suva )',
            '540 – 540 / 540 E – 540 / 1.000',
            'Sinhro PTO ',
            'Opciono',
            'Pokazivač brzine na tabli',
            'Osnovno',
        ],


        left4Title: 'Prednje kačenje u tri tačke, Kvačilo, Kočnice',
        table4: [
            'Maksimalni kapacitet podizanja',
            '2.400 kg',
            'PTO',
            '1,100 rpm',
            'Suvo, nazavisno sa duplim keramičkim diskom',
            '11”',
            'Kontrola',
            'Mehaničke i hidraulične, 10 diskova u ulju ',
        ],




        left5Title: 'Blokada difernecijala, Prednji most, Zadnji most',
        table5: [
            'Tip',
            'Mehaničko',
            'Uključenje',
            'Elektrohidraulično',
            'Maksimalni ugao zaokretanja',
            '52 ⁰',
            'Ugao oscilacija',
            '7 ⁰',
            'Razmak između prirubnice',
            '1,325 mm',
            'Uključenje 4 WD',
            'Elektrohidraulično',
            'Diferencijal',
            'Samo-zaključavanje',
            'Tip',
            'Trkači',
            'Odnos',
            '6:1',
            'Razdaljina prirubnica',
            '1,242 mm',
        ],


        left6Title: 'Hidraulični sistem, Zadnje kačenje tri tačke',
        table6: [
            'Kapacitet pumpe ( lit/min )',
            '64.7+28.8',
            'Razvodnik',
            'Kontrola protoka + 1 SE / DE + 1 SE / DE plutajući',
            'Maksimalni kapacitet podizanja',
            '2.400 kg',
            'Podizanje',
            'Mehaničko sa pozicijom, naponom i kontrolu mešanja',
            'Kačenje',
            '2/1/1N',
            'Donje poluge',
            'Brzo spajanje, podesivo',
        ],


        left7Title: 'Kuka za vuču, Prednji tegovi',
        table7: [
            'Klinovi ( osnovno ) | klizno ( opcija )',
            'Kategorija Cuna C ( osnovno ) | Kategorija Cuna C + D2 ( opcija )',
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg ) | 12 elementa x 30 kg ( 360 kg )',
        ],


        left8Title: 'Sa zaštitnim ramom',
        table8: [
            'Platforma',
            'Čvrsta, zvučno izolovana na 4 silent bloka',
            'Zaštitni ram',
            'Obarajući napred',
            'Volan',
            'Fiksni',
            'Sedište',
            'Mehaničko, Pvc',
            'Retrovizor',
            '1 levi retrovizor ( osnovno ) | desni retrovizor – opcija',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu ',
            'Srpski jezik'

        ],

        left9Title: 'Dimenzije traktora sa kabinom',
        table9: [
            'Ukupna dužina traktora bez tegova',
            '3.864 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.172 mm',
            'Max i min širina traktora sa zadnje strane',
            '1.868 mm / 1.418 mm',
            'Max i min širina traktora sa prednje strane',
            '1.672 mm / 1.556 mm ',
            'Visina sa podignutim ramom ',
            '2.390 mm',
            'Osnova tačka ',
            '2.074 mm',
            'Širina prednjeg traga',
            '1.257 mm / 1.373 mm',
            'Širina zadnjeg traga',
            '1.024 mm / 1.474 mm',
            'Maksimalna visina haube',
            '1.250 mm',
            'Klirens ',
            'prednji: 230mm  | zadnji: 210 mm',
            'Ukupna težina traktora bez tegova',
            '2.600 kg',
            'Dimenzija guma',
            '260 / 70R16 prednje | 380 / 70R20 zadnje'
        ],


        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '7',
        nameUrl: 'agricube-frutteto-basso-90fb',
        productHeader: 'Agricube Frutteto Basso – 90FB',
        className: `agricube-frutteto-basso-90fb-img`,
        desc1: 'Nizak centar gravitacije i niskog profila čine ga pogodnim za upotrebu u brdovitim i planinskim terenima.',
        desc2: 'Frutteto Largo (Voćar Široki) – svestran , robustan i visokih performansi su pridevi koji najbolje opisuju ovaj novi model , namenjen za upotrebu u rasponu od otvorenih polja do voćnjaka . Nizak centar gravitacije i niskog profila čine ga pogodnim za upotrebu u brdovitim i planinskim terenima , obezbeđujući veću stabilnost od tradicionalnih specijalnih tegljača .',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Frutteto Basso 90FB',

        left1Title: 'Motor, Električni sistem',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo intercooler',
            'Sistem hlađenja',
            'Vodeno hlađenje ',
            'Max snaga ISO kW/ks',
            '65 / 88,4',
            'Snaga ISO na vratilu kW/ks',
            '55 / 75',
            'Obrtaji za max snagu',
            '2.300',
            'Obr.za max o moment',
            '1.250',
            'Obrtni moment max',
            '310 Nm@1.250rpm',
            'Rezerva obrt.mom.',
            '36 %',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Kapacitet rezervoara goriva sa prednjim PTO',
            '52,3 l',
            'Auspuh',
            'Horizontalni',
            'Akumulator',
            '100 Ah',
            'Alternator',
            '80 A',
            'Pokretni motor',
            '4,2 kW'
        ],


        left2Title: 'Menjač',
        table2: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '3 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '0,5 km/h sa 24” zadnja guma',
            'Maksimalna brzina traktora',
            '42 km/h sa 24” zadnja guma',
        ],


        left3Title: 'Mehanička snaga zatvorena servo kontrolom',
        table3: [
            'Brzina ( disk lamela suva )',
            '540 – 540 / 540 E – 540 / 1.000',
            'Sinhro PTO ',
            'Opciono',
            'Pokazivač brzine na tabli',
            'Osnovno',
        ],


        left4Title: 'Prednje kačenje u tri tačke, Kvačilo, Kočnice',
        table4: [
            'Maksimalni kapacitet podizanja',
            '2.400 kg',
            'PTO',
            '1,100 rpm',
            'Suvo, nazavisno sa duplim keramičkim diskom',
            '11”',
            'Kontrola',
            'Mehaničke i hidraulične, 10 diskova u ulju ',
        ],




        left5Title: 'Blokada difernecijala, Prednji most, Zadnji most',
        table5: [
            'Tip',
            'Mehaničko',
            'Uključenje',
            'Elektrohidraulično',
            'Maksimalni ugao zaokretanja',
            '52 ⁰',
            'Ugao oscilacija',
            '7 ⁰',
            'Razmak između prirubnice',
            '1,325 mm',
            'Uključenje 4 WD',
            'Elektrohidraulično',
            'Diferencijal',
            'Samo-zaključavanje',
            'Tip',
            'Trkači',
            'Odnos',
            '6:1',
            'Razdaljina prirubnica',
            '1,242 mm',
        ],


        left6Title: 'Hidraulični sistem, Zadnje kačenje tri tačke',
        table6: [
            'Kapacitet pumpe ( lit/min )',
            '64.7+28.8',
            'Razvodnik',
            'Kontrola protoka + 1 SE / DE + 1 SE / DE plutajući',
            'Maksimalni kapacitet podizanja',
            '2.400 kg',
            'Podizanje',
            'Mehaničko sa pozicijom, naponom i kontrolu mešanja',
            'Kačenje',
            '2/1/1N',
            'Donje poluge',
            'Brzo spajanje, podesivo',
        ],


        left7Title: 'Kuka za vuču, Prednji tegovi',
        table7: [
            'Klinovi ( osnovno ) | klizno ( opcija )',
            'Kategorija Cuna C ( osnovno ) | Kategorija Cuna C + D2 ( opcija )',
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg ) | 12 elementa x 30 kg ( 360 kg )',
        ],


        left8Title: 'Sa zaštitnim ramom',
        table8: [
            'Platforma',
            'Čvrsta, zvučno izolovana na 4 silent bloka',
            'Zaštitni ram',
            'Obarajući napred',
            'Volan',
            'Fiksni',
            'Sedište',
            'Mehaničko, Pvc',
            'Retrovizor',
            '1 levi retrovizor ( osnovno ) | desni retrovizor – opcija',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu ',
            'Srpski jezik'

        ],

        left9Title: 'Dimenzije traktora sa kabinom',
        table9: [
            'Ukupna dužina traktora bez tegova',
            '3.864 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.172 mm',
            'Max i min širina traktora sa zadnje strane',
            '1.868 mm / 1.418 mm',
            'Max i min širina traktora sa prednje strane',
            '1.672 mm / 1.556 mm ',
            'Visina sa podignutim ramom ',
            '2.390 mm',
            'Osnova tačka ',
            '2.074 mm',
            'Širina prednjeg traga',
            '1.257 mm / 1.373 mm',
            'Širina zadnjeg traga',
            '1.024 mm / 1.474 mm',
            'Maksimalna visina haube',
            '1.250 mm',
            'Klirens ',
            'prednji: 230mm  | zadnji: 210 mm',
            'Ukupna težina traktora bez tegova',
            '2.600 kg',
            'Dimenzija guma',
            '260 / 70R16 prednje | 380 / 70R20 zadnje'
        ],

    },
    {
        _id: '8',
        nameUrl: 'agricube-vigneto-largo-basso-80vlb',
        productHeader: 'Agricube Vigneto Largo Basso – 80VLB',
        className: `agricube-vigneto-largo-basso-80vlb-img`,
        desc1: 'Najviše odgovara za one koji zahtevaju jedan traktor koji kombinuje osobine moći i pouzdanosti.',
        desc2: 'Vigneto Largo Basso (široki vinogradar niski) – širok Vinograd Niski, zahvaljujući svojim karakteristikama, je kolega-saradnik najviše odgovara za one koji zahtevaju jedan traktor koji kombinuje osobine moći i pouzdanosti uz kompaktnost visine i širine . Zadržavajući kompaktnost veličini traktora Niskog Voćara verziji Široki Vinograd Niski je odlikuje širinom prednje osovine od 1155mm , tako dobijajući ukupan minimum spoljne mere 1350mm.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Vigneto Largo Basso 80VLB',

        left1Title: 'Motor',
        table1: [
            'Motor, proizvođač',
            'FPT, F5C EURO IIIA',
            'Maksimalna snaga ISO kW/ks',
            '55 kW / 74,8 ks',
            'Kubika / broj cilindra',
            '3200 cc / 4 turbo',
        ],



        left2Title: 'Menjač',
        table2: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '0,5 km/h',
            'Maksimalna brzina traktora',
            '40 km/h',
        ],


        left3Title: 'Kardansko vratilo',
        table3: [
            'Brzina ( disk lamela suva )',
            '540 / 540 E – 540 / 1000 rpm',
            'Sinhronizovan PTO  ',
            'Opcija za 24+24 / Standardno za 24+12',
        ],

        left4Title: 'Hidraulični sistem',
        table4: [
            'Kapacitet pumpe ( lit/min )',
            '64.7 + 28.9 l/min',

        ],


        left5Title: 'Kačenje u tri tačke',
        table5: [
            'Kačenje u tri tačke',
            'CAT 2 / 1 / 1N',
            'Sedište vozača',
            'Predni nosač zaštitni ram',
            'Gume',
            'Prednje 280 / 70R16 | Zadnje 360 / 70R24',

        ],

        left6Title: 'Dimenzije traktora',
        table6: [
            'Dužina ( bez tegova )',
            '3840 mm',
            'Visina',
            '1000 mm do vozačevog sedišta / 1250 mm poklopca motora / 2457 mm podignut zaštitni ram',
            'Međuosovinsko rastojanje',
            '2085 mm',
            'Ukupna širina ( min/max )',
            '1350 mm / 1577 mm',
        ],

        left7Title: 'Tabela kombinacije guma',
        table7: [
            'Prednje ',
            '280 / 70R16 | 280 / 70R16 | 260 / 70R16 |  280 / 70R18',
            'Zadnje',
            '360 / 70R24 | 380 / 70R24 | 380 / 70R20 |  440 / 65R24'
        ],


        left8Title: 'Gume',
        table8: [
            'Prednje ',
            '280 / 70R16',
            'Zadnje',
            '360 / 70R24',

        ],


        left9Title: 'Sedište vozača',
        table9: [
            'Sedište vozača',
            'Predni nosač zaštitni ram'
        ],


        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '9',
        nameUrl: 'agricube-vigneto-largo-basso-90vlb',
        productHeader: 'Agricube Vigneto Largo Basso – 90VLB',
        className: `agricube-vigneto-largo-basso-90vlb-img`,
        desc1: 'Najviše odgovara za one koji zahtevaju jedan traktor koji kombinuje osobine moći i pouzdanosti.',
        desc2: 'Vigneto Largo Basso (široki vinogradar niski) – širok Vinograd Niski, zahvaljujući svojim karakteristikama, je kolega-saradnik najviše odgovara za one koji zahtevaju jedan traktor koji kombinuje osobine moći i pouzdanosti uz kompaktnost visine i širine . Zadržavajući kompaktnost veličini traktora Niskog Voćara verziji Široki Vinograd Niski je odlikuje širinom prednje osovine od 1155mm , tako dobijajući ukupan minimum spoljne mere 1350mm.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Vigneto Largo Basso 90VLB',

        left1Title: 'Motor',
        table1: [
            'Motor, proizvođač',
            'FPT, F5C EURO IIIA',
            'Maksimalna snaga ISO kW/ks',
            '65 kW / 88,4 ks',
            'Kubika / broj cilindra',
            '3200 cc / 4 turbo itercooler',
        ],



        left2Title: 'Menjač',
        table2: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '0,5 km/h',
            'Maksimalna brzina traktora',
            '40 km/h',
        ],


        left3Title: 'Kardansko vratilo',
        table3: [
            'Brzina ( disk lamela suva )',
            '540 / 540 E – 540 / 1000 rpm',
            'Sinhronizovan PTO  ',
            'Opcija za 24+24 / Standardno za 24+12',
        ],

        left4Title: 'Hidraulični sistem',
        table4: [
            'Kapacitet pumpe ( lit/min )',
            '64.7 + 28.9 l/min',

        ],


        left5Title: 'Kačenje u tri tačke',
        table5: [
            'Kačenje u tri tačke',
            'CAT 2 / 1 / 1N',
            'Sedište vozača',
            'Predni nosač zaštitni ram',
            'Gume',
            'Prednje 280 / 70R16 | Zadnje 360 / 70R24',

        ],

        left6Title: 'Dimenzije traktora',
        table6: [
            'Dužina ( bez tegova )',
            '3840 mm',
            'Visina',
            '1000 mm do vozačevog sedišta / 1250 mm poklopca motora / 2457 mm podignut zaštitni ram',
            'Međuosovinsko rastojanje',
            '2085 mm',
            'Ukupna širina ( min/max )',
            '1350 mm / 1577 mm',
        ],

        left7Title: 'Tabela kombinacije guma',
        table7: [
            'Prednje ',
            '280 / 70R16 | 280 / 70R16 | 260 / 70R16 |  280 / 70R18',
            'Zadnje',
            '360 / 70R24 | 380 / 70R24 | 380 / 70R20 |  440 / 65R24'
        ],



        left8Title: 'Gume',
        table8: [
            'Prednje ',
            '280 / 70R16',
            'Zadnje',
            '360 / 70R24',

        ],


        left9Title: 'Sedište vozača',
        table9: [
            'Sedište vozača',
            'Predni nosač zaštitni ram'
        ],

        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '10',
        nameUrl: 'agricube-vigneto-80vl',
        productHeader: 'Agricube Vigneto Largo – 80VL',
        className: `agricube-vigneto-80vl-img`,
        desc1: 'Model Vigneto Largo zadovoljava potrebe današnjih farmera. Postoji značajan spektar konfiguracija, sa FPT motorima od 75, 88 i 100ks.',
        desc2: 'Model Vigneto Largo zadovoljava potrebe današnjih farmera, pružajući praktično i pouzdano rešenje, a istovremeno garantujući dobru udobnost. Postoji značajan spektar konfiguracija, sa FPT motorima od 75, 88 i 100 konjskih snaga i mehaničkim / elektronskim zadnjim dizalicama sa spoljnom kontrolom.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Vigneto Largo 80VL',

        left1Title: 'Motor',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo ',
            'Sistem hlađenja',
            'Vodeno hlađenje',
            'Max snaga ISO kW/ks',
            '55/74,8',
            'PTO snaga ISO kW/ks',
            '46/62',
            'Obrtaji za max snagu',
            '2.300',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Auspuh',
            'Horizontalni',

        ],


        left2Title: 'Mehaničko priključno vratilo',
        table2: [
            'Brzina (disk lamele suv)',
            '540 – 540 / 540 E – 540 / 1.000',
        ],


        left3Title: 'Menjač',
        table3: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '1,5 km/h sa točkovima pozadi 14.9R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 14.9R28',
        ],

        left4Title: 'Prednji tegovi',
        table4: [
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
        ],

        left5Title: 'Sa zaštitnim ramom',
        table5: [
            'Zaštitni ram',
            'Sklapajući napred',
            'Volan',
            'Fiksni | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno, Pvc',
            'Retrovizor',
            'Levi retrovizor ( osnovno ) | Desni retrovizor ( opcija )',
            'Visina sa podignutim ramom',
            '2.533 mm',
            'Težina traktora sa ramom',
            '2,670 kg',

        ],

        left6Title: 'Sa kabinom',
        table6: [
            'Kabina',
            'Nezavisna, zvučna izolacija na 4 tiha bloka sa ventilacijom i grejanjem ( osnovno ) | Klima ( opcija )',
            'Volan',
            'Fiksni ( osnovno ) | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno sa platnom ( osnovno ) | Nezavisno, pneumatsko sa platnom ( opcija )',
            'Retrovizor',
            'Dva retrovizora sa obe strane ( osnovno ) | 1 unutrašnje ogledalo ( opcija )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu',
            'Srpski jezik',
        ],

        left7Title: 'Dimenzije traktora sa kabinom',
        table7: [
            'Ukupna dužina traktora bez tegova',
            '3.991 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.316 mm',
            'Ukupna visina traktora sa kabinom',
            '2.385 mm',
            'Max širina traktora',
            '1,900 mm',
            'Prednji klirens',
            '306 mm',
            'Zadnji klirens',
            '355 mm',
            'Širina prednjeg traga',
            '846 / 1,110 mm',
            'Širina zadnjeg traga',
            '928 / 1,376 mm',
            'Težina traktora sa kabinom',
            '2,905 kg',
        ],

        left8Title: 'Kvačilo',
        table8: [
            'Kvačilo',
            'Nezavisno, suvo, 11”',
        ],


        left9Title: 'Kočnice, Prednji tegovi',
        table9: [
            'Kočnice',
            'Mehaničke i hidraulične integrisane, diskovi u ulju',
            'Maksimalna podizna moć',
            '2.600 kg',
            'Kačenje u tri tačke',
            '1 / 1N / 2 kat.',
            'Opcija',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
        ],




        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '11',
        nameUrl: 'agricube-vigneto-90vl',
        productHeader: 'Agricube Vigneto Largo – 90VL',
        className: `agricube-vigneto-90vl-img`,
        desc1: 'Model Vigneto Largo zadovoljava potrebe današnjih farmera. Postoji značajan spektar konfiguracija, sa FPT motorima od 75, 88 i 100ks.',
        desc2: 'Model Vigneto Largo zadovoljava potrebe današnjih farmera, pružajući praktično i pouzdano rešenje, a istovremeno garantujući dobru udobnost. Postoji značajan spektar konfiguracija, sa FPT motorima od 75, 88 i 100 konjskih snaga i mehaničkim / elektronskim zadnjim dizalicama sa spoljnom kontrolom.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Vigneto Largo 90VL',

        left1Title: 'Motor',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo intercooler	',
            'Sistem hlađenja',
            'Vodeno hlađenje',
            'Max snaga ISO kW/ks',
            '65/88,4',
            'PTO snaga ISO kW/ks',
            '55/75',
            'Obrtaji za max snagu',
            '2.300',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Auspuh',
            'Horizontalni',

        ],


        left2Title: 'Mehaničko priključno vratilo',
        table2: [
            'Brzina (disk lamele suv)',
            '540 – 540 / 540 E – 540 / 1.000',
        ],


        left3Title: 'Menjač',
        table3: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '1,5 km/h sa točkovima pozadi 14.9R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 14.9R28',
        ],

        left4Title: 'Prednji tegovi',
        table4: [
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
        ],

        left5Title: 'Sa zaštitnim ramom',
        table5: [
            'Zaštitni ram',
            'Sklapajući napred',
            'Volan',
            'Fiksni | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno, Pvc',
            'Retrovizor',
            'Levi retrovizor ( osnovno ) | Desni retrovizor ( opcija )',
            'Visina sa podignutim ramom',
            '2.533 mm',
            'Težina traktora sa ramom',
            '2,670 kg',

        ],

        left6Title: 'Sa kabinom',
        table6: [
            'Kabina',
            'Nezavisna, zvučna izolacija na 4 tiha bloka sa ventilacijom i grejanjem ( osnovno ) | Klima ( opcija )',
            'Volan',
            'Fiksni ( osnovno ) | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno sa platnom ( osnovno ) | Nezavisno, pneumatsko sa platnom ( opcija )',
            'Retrovizor',
            'Dva retrovizora sa obe strane ( osnovno ) | 1 unutrašnje ogledalo ( opcija )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu',
            'Srpski jezik',
        ],

        left7Title: 'Dimenzije traktora sa kabinom',
        table7: [
            'Ukupna dužina traktora bez tegova',
            '3.991 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.316 mm',
            'Ukupna visina traktora sa kabinom',
            '2.385 mm',
            'Max širina traktora',
            '1,900 mm',
            'Prednji klirens',
            '306 mm',
            'Zadnji klirens',
            '355 mm',
            'Širina prednjeg traga',
            '846 / 1,110 mm',
            'Širina zadnjeg traga',
            '928 / 1,376 mm',
            'Težina traktora sa kabinom',
            '2,905 kg',
        ],

        left8Title: 'Kvačilo',
        table8: [
            'Kvačilo',
            'Nezavisno, suvo, 11”',
        ],


        left9Title: 'Kočnice, Prednji tegovi',
        table9: [
            'Kočnice',
            'Mehaničke i hidraulične integrisane, diskovi u ulju',
            'Maksimalna podizna moć',
            '2.600 kg',
            'Kačenje u tri tačke',
            '1 / 1N / 2 kat.',
            'Opcija',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
        ],


        brand: 'Carraro',
        category: 'Traktori'
    },
    {
        _id: '12',
        nameUrl: 'agricube-vigneto-100vl',
        productHeader: 'Agricube Vigneto Largo – 100VL',
        className: `agricube-vigneto-100vl-img`,
        desc1: 'Model Vigneto Largo zadovoljava potrebe današnjih farmera. Postoji značajan spektar konfiguracija, sa FPT motorima od 75, 88 i 100ks.',
        desc2: 'Model Vigneto Largo zadovoljava potrebe današnjih farmera, pružajući praktično i pouzdano rešenje, a istovremeno garantujući dobru udobnost. Postoji značajan spektar konfiguracija, sa FPT motorima od 75, 88 i 100 konjskih snaga i mehaničkim / elektronskim zadnjim dizalicama sa spoljnom kontrolom.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Agricube Vigneto Largo 100VL',

        left1Title: 'Motor',
        table1: [
            'Motor, proizvođač',
            'FPT',
            'Tip motora',
            'F5C (Euro III A)',
            'Kubika',
            '3.200 c³',
            'Broj cilind/konfigur.',
            '4, turbo intercooler',
            'Sistem hlađenja',
            'Vodeno hlađenje',
            'Max snaga ISO kW/ks',
            '74/100,6',
            'PTO snaga ISO kW/ks',
            '63/86',
            'Obrtaji za max snagu',
            '2.200',
            'Kapacitet rezervoara goriva',
            '71 l',
            'Auspuh',
            'Horizontalni',

        ],


        left2Title: 'Mehaničko priključno vratilo',
        table2: [
            'Brzina (disk lamele suv)',
            '540 – 540 / 540 E – 540 / 1.000',
        ],


        left3Title: 'Menjač',
        table3: [
            'Ručica menjača',
            'sa strane',
            'Menjač',
            '4 sinhro za svaku brzinu',
            'Kretanje',
            '3 brzine kretanja Spora/Srednja/Brza',
            'Reverzer',
            'mehanički',
            'Minimalna brzina traktora',
            '1,5 km/h sa točkovima pozadi 14.9R28',
            'Maksimalna brzina traktora',
            '30 km/h sa točkovima pozadi 14.9R28',
        ],

        left4Title: 'Prednji tegovi',
        table4: [
            'Opciono',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
        ],

        left5Title: 'Sa zaštitnim ramom',
        table5: [
            'Zaštitni ram',
            'Sklapajući napred',
            'Volan',
            'Fiksni | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno, Pvc',
            'Retrovizor',
            'Levi retrovizor ( osnovno ) | Desni retrovizor ( opcija )',
            'Visina sa podignutim ramom',
            '2.533 mm',
            'Težina traktora sa ramom',
            '2,670 kg',

        ],

        left6Title: 'Sa kabinom',
        table6: [
            'Kabina',
            'Nezavisna, zvučna izolacija na 4 tiha bloka sa ventilacijom i grejanjem ( osnovno ) | Klima ( opcija )',
            'Volan',
            'Fiksni ( osnovno ) | Teleskopski pod uglom ( opcija )',
            'Sedište',
            'Mehaničko, nezavisno sa platnom ( osnovno ) | Nezavisno, pneumatsko sa platnom ( opcija )',
            'Retrovizor',
            'Dva retrovizora sa obe strane ( osnovno ) | 1 unutrašnje ogledalo ( opcija )',
            'Instrument tabla',
            'Multifunkcionalna',
            'Uputstvo za upotrebu',
            'Srpski jezik',
        ],

        left7Title: 'Dimenzije traktora sa kabinom',
        table7: [
            'Ukupna dužina traktora bez tegova',
            '3.991 mm',
            'Ukupna dužina traktora sa tegovima',
            '4.316 mm',
            'Ukupna visina traktora sa kabinom',
            '2.385 mm',
            'Max širina traktora',
            '1,900 mm',
            'Prednji klirens',
            '306 mm',
            'Zadnji klirens',
            '355 mm',
            'Širina prednjeg traga',
            '846 / 1,110 mm',
            'Širina zadnjeg traga',
            '928 / 1,376 mm',
            'Težina traktora sa kabinom',
            '2,905 kg',
        ],


        left8Title: 'Kvačilo',
        table8: [
            'Kvačilo',
            'Nezavisno, suvo, 11”',
        ],


        left9Title: 'Kočnice, Prednji tegovi',
        table9: [
            'Kočnice',
            'Mehaničke i hidraulične integrisane, diskovi u ulju',
            'Maksimalna podizna moć',
            '2.600 kg',
            'Kačenje u tri tačke',
            '1 / 1N / 2 kat.',
            'Opcija',
            '4 elementa x 30 kg ( 120 kg ) | 6 elementa x 30 kg ( 180 kg ) | 10 elementa x 30 kg ( 300 kg )',
        ],



        brand: 'Carraro',
        category: 'Traktori'
    }
]


export const both = [...Carraro];
export { Carraro }

