const Zetor = [
    {
        _id: '1',
        nameUrl: 'zetor-proxima-power-90',
        productHeader: 'Proxima Power 90',
        className: `zetor-proxima-power-90-img`,
        desc1: 'U odnosu na Proximu Classic, Proxima Power ima automatsku transmisiju. Za razliku od konkurencije, Zetor motori su jednostavni.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima Power u standardnoj opremi imaju, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine radne sate lakšim.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Zetor Proxima Power 90',

        left1Title: 'Motor i Menjač',
        table1: [
            'Tip, Stage III A',
            '1205',
            'Nominalna snaga (kW) (2000/25/EC)',
            '64,3',
            'Nominalna snaga (HP)',
            '87',
            'Nominalni broj obrtaja (o/min)',
            '2200',
            'Broj cilindara',
            '4',
            'Broj ventila',
            '8',
            'Turbo kompresor',
            'Da',
            'Prečnik/Hod klipa (mm)',
            '105/120',
            'Zapremina motora (cm³)',
            '4 156',
            'Hlađenje',
            'Vodeno',
            'Maks. obrtni moment (Nm) (2000/25/EC)',
            '370',
            'Rezerva obrtnog momenta (%)',
            '38',
            'Tip Menjača',
            'Mehanički sa 3-stepenim multiplikatorom, elektro-hidraulični reverzer',
            'Reverzer',
            'Pod opterećenjem do 10 km/h',
            'Potpuno sinhronizovan',
            'Da ',
            'Broj stepeni prenosa (napred/nazad)',
            '24 / 24 ',
            'Maks. brzina kretanja (km/h)',
            '40',
        ],

        left2Title: 'Pogon izvodnog vratila i  Hidraulika',
        table2: [
            'Tip',
            'Zavisno / nezavisno',
            'Br obrtaja zadnjeg izvod vratila (o/min)',
            '540/1.000, 540/540E',
            'Br obrtaja prednjeg izvod vratila',
            '1000',
            'Maks. snaga pred. izvod.vratila (kW)',
            '60',
            'Tip Hidraulike',
            'Mehanička sa podešavanje prema položaju (P), otporu (R) ili mešovito(M)',
            'Uređaj za priključivanje oruđa',
            'Kategorija II',
            'Upravljanje',
            'Električno EHR; opciono mehaničko',
            'Maks. podizna moć (kN)',
            '42',
            'Radni pritisak (MPa)',
            '19',
            'Kapacitet pumpe (l)',
            '50',
            'Broj parova izvoda spoljne hidraulike',
            '6+1; opcija 8+1 (samo za EHR), ili 4+1',
            'Poteznice',
            'Modularni sistem, gornja podesiva i donja zakretna',
        ],

        left3Title: 'Kabina',
        table3: [

            'Kabina, Krovni prozor',
            'Standard',
            'Sedište',
            'Mehanički / Pneumatski ogibljeno',
            'Pomoćno sedište',
            'Standard',
            'Upravljač',
            'Podesiv po nagibu i visini',
            'Klima uređaj',
            'Standard, manuelna',
        ],

        left4Title: 'Ostale karakteristike',
        table4: [
            'Pogon',
            '4WD',
            'Upravljanje',
            'Hidrostatičko',
            'Radne/Parking kočnice',
            'Mokre, disk, hidraulično / mehanički upravljane',
            'Prednje kočnice',
            'Mokre, disk u prednjem točku',
            'Kočnice za prikolice',
            '1+2 pneumatske (opcija hidraulične)',
            'Maks. prednji teg (kg)',
            '466',
            'Maks. teg zadnjih točkova (kg)',
            '270',
            'Rezervoar za gorivo (l)',
            '180',
            'Prednji blatobrani',
            'Fiksni',
            'Grejač zadnjeg stakla',
            'Opcija',
            'Priprema za radio',
            'Standard',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Masa traktora spremnog za rad bez prednjeg tega (kg)',
            '4.014–4.257',
            'Dužina (mm)',
            '4.941',
            'Širina (mm)',
            '2.319',
            'Visina (mm)',
            '2.738',
            'Međuosovinsko rastojanje (mm)',
            '2.442',
            'Prednji točak (mm)',
            '320/85R24',
            'Zadnji točak (mm)',
            '420/85R34',
        ],


        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Elektro-hidraulika BOSH HITCH-TRONIC',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Kapacitet hidro-pumpe 60 l/min',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo',
        ]
    },
    {
        _id: '2',
        nameUrl: 'zetor-proxima-power-100',
        productHeader: ' Proxima Power 100',
        className: `zetor-proxima-power-100-img`,
        desc1: 'U odnosu na Proximu Classic, Proxima Power ima automatsku transmisiju. Za razliku od konkurencije, Zetor motori su jednostavni.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima Power u standardnoj opremi imaju, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine radne sate lakšim.',
        teh_kar: 'Tehničke Karakteristike',


        t1LeftHeader: 'Zetor Proxima Power 100',

        left1Title: 'Motor i Menjač',
        table1: [
            'Tip, Stage III A',
            '1005',
            'Nominalna snaga (kW) (2000/25/EC)',
            '70,3',
            'Nominalna snaga (HP)',
            '96',
            'Nominalni broj obrtaja (o/min)',
            '2200',
            'Broj cilindara',
            '4',
            'Broj ventila',
            '8',
            'Turbo kompresor',
            'Da',
            'Prečnik/Hod klipa (mm)',
            '105/120',
            'Zapremina motora (cm³)',
            '4 156',
            'Hlađenje',
            'Vodeno',
            'Maks. obrtni moment (Nm) (2000/25/EC)',
            '429',
            'Rezerva obrtnog momenta (%)',
            '46',
            'Tip Menjača',
            'Mehanički sa 3-stepenim multiplikatorom, elektro-hidraulični reverzer',
            'Reverzer',
            'Pod opterećenjem do 10 km/h',
            'Potpuno sinhronizovan',
            'Da ',
            'Broj stepeni prenosa (napred/nazad)',
            '24 / 24 ',
            'Maks. brzina kretanja (km/h)',
            '40',
        ],

        left2Title: 'Pogon izvodnog vratila i  Hidraulika',
        table2: [
            'Tip',
            'Zavisno / nezavisno',
            'Br obrtaja zadnjeg izvod vratila (o/min)',
            '540/1.000, 540/540E',
            'Br obrtaja prednjeg izvod vratila',
            '1000',
            'Maks. snaga pred. izvod.vratila (kW)',
            '60',
            'Tip Hidraulike',
            'Mehanička sa podešavanje prema položaju (P), otporu (R) ili mešovito(M)',
            'Uređaj za priključivanje oruđa',
            'Kategorija II',
            'Upravljanje',
            'Električno EHR; opciono mehaničko',
            'Maks. podizna moć (kN)',
            '42',
            'Radni pritisak (MPa)',
            '19',
            'Kapacitet pumpe (l)',
            '50',
            'Broj parova izvoda spoljne hidraulike',
            '6+1; opcija 8+1 (samo za EHR), ili 4+1',
            'Poteznice',
            'Modularni sistem, gornja podesiva i donja zakretna',
        ],

        left3Title: 'Kabina',
        table3: [

            'Kabina, Krovni prozor',
            'Standard',
            'Sedište',
            'Mehanički / Pneumatski ogibljeno',
            'Pomoćno sedište',
            'Standard',
            'Upravljač',
            'Podesiv po nagibu i visini',
            'Klima uređaj',
            'Standard, manuelna',
        ],

        left4Title: 'Ostale karakteristike',
        table4: [
            'Pogon',
            '4WD',
            'Upravljanje',
            'Hidrostatičko',
            'Radne/Parking kočnice',
            'Mokre, disk, hidraulično / mehanički upravljane',
            'Prednje kočnice',
            'Mokre, disk u prednjem točku',
            'Kočnice za prikolice',
            '1+2 pneumatske (opcija hidraulične)',
            'Maks. prednji teg (kg)',
            '466',
            'Maks. teg zadnjih točkova (kg)',
            '270',
            'Rezervoar za gorivo (l)',
            '180',
            'Prednji blatobrani',
            'Fiksni',
            'Grejač zadnjeg stakla',
            'Opcija',
            'Priprema za radio',
            'Standard',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Masa traktora spremnog za rad bez prednjeg tega (kg)',
            '4.014–4.257',
            'Dužina (mm)',
            '4.941',
            'Širina (mm)',
            '2.319',
            'Visina (mm)',
            '2.738',
            'Međuosovinsko rastojanje (mm)',
            '2.442',
            'Prednji točak (mm)',
            '320/85R24',
            'Zadnji točak (mm)',
            '420/85R34',
        ],


        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Elektro-hidraulika BOSH HITCH-TRONIC',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Kapacitet hidro-pumpe 60 l/min',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo',
        ]
    },
    {
        _id: '3',
        nameUrl: 'zetor-proxima-power-110',
        productHeader: ' Proxima Power 110',
        className: `zetor-proxima-power-110-img`,
        desc1: 'U odnosu na Proximu Classic, Proxima Power ima automatsku transmisiju. Za razliku od konkurencije, Zetor motori su jednostavni.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima Power u standardnoj opremi imaju, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine radne sate lakšim.',
        teh_kar: 'Tehničke Karakteristike',


        t1LeftHeader: 'Zetor Proxima Power 110',

        left1Title: 'Motor i Menjač',
        table1: [
            'Tip, Stage III A',
            '1305',
            'Nominalna snaga (kW) (2000/25/EC)',
            '78,4',
            'Nominalna snaga (HP)',
            '106',
            'Nominalni broj obrtaja (o/min)',
            '2200',
            'Broj cilindara',
            '4',
            'Broj ventila',
            '8',
            'Turbo kompresor',
            'Da',
            'Prečnik/Hod klipa (mm)',
            '105/120',
            'Zapremina motora (cm³)',
            '4 156',
            'Hlađenje',
            'Vodeno',
            'Maks. obrtni moment (Nm) (2000/25/EC)',
            '461',
            'Rezerva obrtnog momenta (%)',
            '40',
            'Tip Menjača',
            'Mehanički sa 3-stepenim multiplikatorom, elektro-hidraulični reverzer',
            'Reverzer',
            'Pod opterećenjem do 10 km/h',
            'Potpuno sinhronizovan',
            'Da ',
            'Broj stepeni prenosa (napred/nazad)',
            '24 / 24 ',
            'Maks. brzina kretanja (km/h)',
            '40',
        ],

        left2Title: 'Pogon izvodnog vratila i  Hidraulika',
        table2: [
            'Tip',
            'Zavisno / nezavisno',
            'Br obrtaja zadnjeg izvod vratila (o/min)',
            '540/1.000, 540/540E',
            'Br obrtaja prednjeg izvod vratila',
            '1000',
            'Maks. snaga pred. izvod.vratila (kW)',
            '60',
            'Tip Hidraulike',
            'Mehanička sa podešavanje prema položaju (P), otporu (R) ili mešovito(M)',
            'Uređaj za priključivanje oruđa',
            'Kategorija II',
            'Upravljanje',
            'Električno EHR; opciono mehaničko',
            'Maks. podizna moć (kN)',
            '42',
            'Radni pritisak (MPa)',
            '19',
            'Kapacitet pumpe (l)',
            '50',
            'Broj parova izvoda spoljne hidraulike',
            '6+1; opcija 8+1 (samo za EHR), ili 4+1',
            'Poteznice',
            'Modularni sistem, gornja podesiva i donja zakretna',
        ],

        left3Title: 'Kabina',
        table3: [

            'Kabina, Krovni prozor',
            'Standard',
            'Sedište',
            'Mehanički / Pneumatski ogibljeno',
            'Pomoćno sedište',
            'Standard',
            'Upravljač',
            'Podesiv po nagibu i visini',
            'Klima uređaj',
            'Standard, manuelna',
        ],

        left4Title: 'Ostale karakteristike',
        table4: [
            'Pogon',
            '4WD',
            'Upravljanje',
            'Hidrostatičko',
            'Radne/Parking kočnice',
            'Mokre, disk, hidraulično / mehanički upravljane',
            'Prednje kočnice',
            'Mokre, disk u prednjem točku',
            'Kočnice za prikolice',
            '1+2 pneumatske (opcija hidraulične)',
            'Maks. prednji teg (kg)',
            '466',
            'Maks. teg zadnjih točkova (kg)',
            '270',
            'Rezervoar za gorivo (l)',
            '180',
            'Prednji blatobrani',
            'Fiksni',
            'Grejač zadnjeg stakla',
            'Opcija',
            'Priprema za radio',
            'Standard',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Masa traktora spremnog za rad bez prednjeg tega (kg)',
            '4.014–4.257',
            'Dužina (mm)',
            '4.941',
            'Širina (mm)',
            '2.319',
            'Visina (mm)',
            '2.738',
            'Međuosovinsko rastojanje (mm)',
            '2.442',
            'Prednji točak (mm)',
            '320/85R24',
            'Zadnji točak (mm)',
            '420/85R34',
        ],


        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Elektro-hidraulika BOSH HITCH-TRONIC',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Kapacitet hidro-pumpe 60 l/min',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo',
        ]
    },
    {
        _id: '4',
        nameUrl: 'zetor-proxima-power-120',
        productHeader: ' Proxima Power 120',
        className: `zetor-proxima-power-120-img`,
        desc1: 'U odnosu na Proximu Classic, Proxima Power ima automatsku transmisiju. Za razliku od konkurencije, Zetor motori su jednostavni.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima Power u standardnoj opremi imaju, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine radne sate lakšim.',
        teh_kar: 'Tehničke Karakteristike',


        t1LeftHeader: 'Zetor Proxima Power 120',

        left1Title: 'Motor i Menjač',
        table1: [
            'Tip, Stage III A',
            '1405',
            'Nominalna snaga (kW) (2000/25/EC)',
            '86,2',
            'Nominalna snaga (HP)',
            '117',
            'Nominalni broj obrtaja (o/min)',
            '2200',
            'Broj cilindara',
            '4',
            'Broj ventila',
            '8',
            'Turbo kompresor',
            'Da',
            'Prečnik/Hod klipa (mm)',
            '105/120',
            'Zapremina motora (cm³)',
            '4 156',
            'Hlađenje',
            'Vodeno',
            'Maks. obrtni moment (Nm) (2000/25/EC)',
            '493',
            'Rezerva obrtnog momenta (%)',
            '37',
            'Tip Menjača',
            'Mehanički sa 3-stepenim multiplikatorom, elektro-hidraulični reverzer',
            'Reverzer',
            'Pod opterećenjem do 10 km/h',
            'Potpuno sinhronizovan',
            'Da ',
            'Broj stepeni prenosa (napred/nazad)',
            '24 / 24 ',
            'Maks. brzina kretanja (km/h)',
            '40',
        ],

        left2Title: 'Pogon izvodnog vratila i  Hidraulika',
        table2: [
            'Tip',
            'Zavisno / nezavisno',
            'Br obrtaja zadnjeg izvod vratila (o/min)',
            '540/1.000, 540/540E',
            'Br obrtaja prednjeg izvod vratila',
            '1000',
            'Maks. snaga pred. izvod.vratila (kW)',
            '60',
            'Tip Hidraulike',
            'Mehanička sa podešavanje prema položaju (P), otporu (R) ili mešovito(M)',
            'Uređaj za priključivanje oruđa',
            'Kategorija II',
            'Upravljanje',
            'Električno EHR; opciono mehaničko',
            'Maks. podizna moć (kN)',
            '42',
            'Radni pritisak (MPa)',
            '19',
            'Kapacitet pumpe (l)',
            '50',
            'Broj parova izvoda spoljne hidraulike',
            '6+1; opcija 8+1 (samo za EHR), ili 4+1',
            'Poteznice',
            'Modularni sistem, gornja podesiva i donja zakretna',
        ],

        left3Title: 'Kabina',
        table3: [

            'Kabina, Krovni prozor',
            'Standard',
            'Sedište',
            'Mehanički / Pneumatski ogibljeno',
            'Pomoćno sedište',
            'Standard',
            'Upravljač',
            'Podesiv po nagibu i visini',
            'Klima uređaj',
            'Standard, manuelna',
        ],

        left4Title: 'Ostale karakteristike',
        table4: [
            'Pogon',
            '4WD',
            'Upravljanje',
            'Hidrostatičko',
            'Radne/Parking kočnice',
            'Mokre, disk, hidraulično / mehanički upravljane',
            'Prednje kočnice',
            'Mokre, disk u prednjem točku',
            'Kočnice za prikolice',
            '1+2 pneumatske (opcija hidraulične)',
            'Maks. prednji teg (kg)',
            '466',
            'Maks. teg zadnjih točkova (kg)',
            '270',
            'Rezervoar za gorivo (l)',
            '180',
            'Prednji blatobrani',
            'Fiksni',
            'Grejač zadnjeg stakla',
            'Opcija',
            'Priprema za radio',
            'Standard',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Masa traktora spremnog za rad bez prednjeg tega (kg)',
            '4.014–4.257',
            'Dužina (mm)',
            '4.941',
            'Širina (mm)',
            '2.319',
            'Visina (mm)',
            '2.738',
            'Međuosovinsko rastojanje (mm)',
            '2.442',
            'Prednji točak (mm)',
            '320/85R24',
            'Zadnji točak (mm)',
            '420/85R34',
        ],


        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Elektro-hidraulika BOSH HITCH-TRONIC',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Kapacitet hidro-pumpe 60 l/min',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo',
        ]
    },
    {
        _id: '5',
        nameUrl: 'zetor-proxima-80',
        productHeader: ' Proxima 80',
        className: `zetor-proxima-80-img`,
        desc1: 'Za razliku od konkurencije, Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima u standardnoj opremi imaju mehanički reverzer, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine sate rada lakšim.',
        teh_kar: 'Tehničke Karakteristike',


        t1LeftHeader: 'Zetor Proxima 80',

        left1Title: 'Motor',
        table1: [
            'Tip, Stage III A',
            'Z-1105',
            'Snaga prema ISO 2000/25 (kW/KS)',
            '55,6 / 76	',
            'Nominalni broj obrtaja (o/min)',
            '2.200',
            'Turbo kompresor',
            'da',
            ' Zapremina motora (cm3)',
            '4.156',
            'Maks. obrtni moment (Nm) / rezerva (%)',
            '271 / 36',
        ],

        left2Title: 'Transmisija',
        table2: [
            'Tip',
            'Mehanička',
            'Reverzer',
            'Komanda ispod volana',
            'Menjač',
            'Potpuno sinhronizovan',
            'Broj stepeni prenosa (napred/nazad)',
            '12/12',
            'Maksimalna brzina kretanja (km/h)',
            '30 (opcija 40)',
        ],

        left3Title: 'Priključno vratilo',
        table3: [
            'Tip',
            'Zavisno / nezavisno',
            'Broj obrtaja (o/min)',
            '540 / 540E ili 540 / 1000',
        ],

        left4Title: 'Hidraulika',
        table4: [
            'Uređaj za priključenje “u tri tačke”',
            'kategorija CAT II',
            'Podizna moć na krajevima poluga (kN)',
            'standard 4.2',
            'Kapacitet pumpe (l/min)',
            '50',
            'Broj priključaka spoljne hidraulike',
            '4+1 (opcije: 2+1 ili 6+1)',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Maksimalna težina (kg)',
            '4.546',
            'Dužina/širina/visina (mm)',
            '4.710 / 2.319 / 2.725',
            'Međuosovinsko rastojanje (mm)',
            '2.308',
            'Zapremina rezervoara goriva (l)',
            '124',
            'Prednji točkovi',
            '11.2-R24 ili 12.4-R24',
            'Zadnji točkovi',
            '13.6-R36 ili 16.9-R34',
        ],


        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Synchhro Shuttle box (12+12), mehanički reverzer',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko kvačilo',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Spoljna kontrola hidraulike',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Koncepcija 2WD',
            ' - Vazdušno ogibljeno sedište',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo'
        ]
    },
    {
        _id: '6',
        nameUrl: 'zetor-proxima-90',
        productHeader: ' Proxima 90',
        className: `zetor-proxima-90-img`,
        desc1: 'Za razliku od konkurencije, Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima u standardnoj opremi imaju mehanički reverzer, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine sate rada lakšim.',
        teh_kar: 'Tehničke Karakteristike',


        t1LeftHeader: 'Zetor Proxima 90',

        left1Title: 'Motor',
        table1: [
            'Tip, Stage III A',
            'Z-1205',
            'Snaga prema ISO 2000/25 (kW/KS)',
            '64,3 / 87',
            'Nominalni broj obrtaja (o/min)',
            '2.200',
            'Turbo kompresor',
            'da',
            ' Zapremina motora (cm3)',
            '4.156',
            'Maks. obrtni moment (Nm) / rezerva (%)',
            '317 / 35',
        ],

        left2Title: 'Transmisija',
        table2: [
            'Tip',
            'Mehanička',
            'Reverzer',
            'Komanda ispod volana',
            'Menjač',
            'Potpuno sinhronizovan',
            'Broj stepeni prenosa (napred/nazad)',
            '12/12',
            'Maksimalna brzina kretanja (km/h)',
            '30 (opcija 40)',
        ],

        left3Title: 'Priključno vratilo',
        table3: [
            'Tip',
            'Zavisno / nezavisno',
            'Broj obrtaja (o/min)',
            '540 / 540E ili 540 / 1000',
        ],

        left4Title: 'Hidraulika',
        table4: [
            'Uređaj za priključenje “u tri tačke”',
            'kategorija CAT II',
            'Podizna moć na krajevima poluga (kN)',
            'standard 4.2',
            'Kapacitet pumpe (l/min)',
            '50',
            'Broj priključaka spoljne hidraulike',
            '4+1 (opcije: 2+1 ili 6+1)',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Maksimalna težina (kg)',
            '4.546',
            'Dužina/širina/visina (mm)',
            '4.710 / 2.319 / 2.725',
            'Međuosovinsko rastojanje (mm)',
            '2.308',
            'Zapremina rezervoara goriva (l)',
            '124',
            'Prednji točkovi',
            '11.2-R24 ili 12.4-R24',
            'Zadnji točkovi',
            '13.6-R36 ili 16.9-R34',
        ],

        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Synchhro Shuttle box (12+12), mehanički reverzer',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko kvačilo',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Spoljna kontrola hidraulike',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Koncepcija 2WD',
            ' - Vazdušno ogibljeno sedište',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo'
        ]
    },
    {
        _id: '7',
        nameUrl: 'zetor-proxima-100',
        productHeader: ' Proxima 100',
        className: `zetor-proxima-100-img`,
        desc1: 'Za razliku od konkurencije, Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima.',
        desc2: 'Zetor motori su jednostavni, bez elektronike i potrebe za dodatnim aditivima, pouzdani su i jeftini za održavanje. Modeli Proxima u standardnoj opremi imaju mehanički reverzer, veoma komfornu kabinu, prostranu, koja pruža idealnu preglednost što uz ergonomski postavljene komande čine sate rada lakšim.',
        teh_kar: 'Tehničke Karakteristike',


        t1LeftHeader: 'Zetor Proxima 100',

        left1Title: 'Motor',
        table1: [
            'Tip, Stage III A',
            'Z-1005',
            'Snaga prema ISO 2000/25 (kW/KS)',
            '70,3 / 96',
            'Nominalni broj obrtaja (o/min)',
            '2.200',
            'Turbo kompresor',
            'da',
            ' Zapremina motora (cm3)',
            '4.156',
            'Maks. obrtni moment (Nm) / rezerva (%)',
            '370 / 38',
        ],

        left2Title: 'Transmisija',
        table2: [
            'Tip',
            'Mehanička',
            'Reverzer',
            'Komanda ispod volana',
            'Menjač',
            'Potpuno sinhronizovan',
            'Broj stepeni prenosa (napred/nazad)',
            '12/12',
            'Maksimalna brzina kretanja (km/h)',
            '30 (opcija 40)',
        ],

        left3Title: 'Priključno vratilo',
        table3: [
            'Tip',
            'Zavisno / nezavisno',
            'Broj obrtaja (o/min)',
            '540 / 540E ili 540 / 1000',
        ],

        left4Title: 'Hidraulika',
        table4: [
            'Uređaj za priključenje “u tri tačke”',
            'kategorija CAT II',
            'Podizna moć na krajevima poluga (kN)',
            'standard 4.2',
            'Kapacitet pumpe (l/min)',
            '50',
            'Broj priključaka spoljne hidraulike',
            '4+1 (opcije: 2+1 ili 6+1)',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Maksimalna težina (kg)',
            '4.546',
            'Dužina/širina/visina (mm)',
            '4.710 / 2.319 / 2.725',
            'Međuosovinsko rastojanje (mm)',
            '2.308',
            'Zapremina rezervoara goriva (l)',
            '124',
            'Prednji točkovi',
            '11.2-R24 ili 12.4-R24',
            'Zadnji točkovi',
            '13.6-R36 ili 16.9-R34',
        ],

        standardOprema1: 'Standardna oprema',
        standardLi1: [
            ' - Mehanički ogibljeno sedište + pomoćno sedište',
            ' - Klima uređaj',
            ' - Podesiv volan',
            ' - Prednja i zadnja dodatna radna svetla',
            ' - Karbonski filter',
            ' - Synchhro Shuttle box (12+12), mehanički reverzer',
            ' - Radio',
            ' - Kompresor',
            ' - Pneumatska instalacija za kočenje prikolica, 1-kružni i 2-kružni sistem',
            ' - Pneumatsko kvačilo',
            ' - Pneumatsko uključenje blokade diferencijala i prednje vuče',
            ' - Prednji blatobrani',
            ' - Prednji tegovi, set 200 ili 400 kg',
            ' - Tegovi na zadnjim točkovima, set 90 ili 150 kg',
            ' - Izvodi spoljne hidraulike 2 para (4+1)',
            ' - Gornja okretna i donja klateća poteznica',
            ' - Automatske hidraulične poluge CAT 2',
            ' - Spoljna kontrola hidraulike',
        ],

        standardOprema2: 'Dodatna oprema',
        standardLi2: [
            ' - Izbor dimenzije pneumatika',
            ' - Koncepcija 2WD',
            ' - Vazdušno ogibljeno sedište',
            ' - Dodatne poteznice',
            ' - Dodatni par spoljne hidraulike',
            ' - Prednja hidraulika',
            ' - Prednje priključno vratilo'
        ]
    },
    {
        _id: '8',
        nameUrl: 'zetor-major-80',
        productHeader: ' Major 80',
        className: `zetor-major-80-img`,
        desc1: 'Zasnovan je na modelu istog imena koji se dokazao kao jedan od najuspešnijih traktora u istoriji Zetora.',
        desc2: 'Traktor pruža veoma visok komfor, a ono što ga čini jedinstvenim je njegova jednostavnost, izdržljivost i niski troškovi održavanja. Od početka 2018. u ponudi se može naći isti model sa ugrađenim “stage” III B motorom.',
        teh_kar: 'Tehničke Karakteristike',

        t1LeftHeader: 'Zetor Major 80',

        left1Title: 'Motor',
        table1: [
            'Tip, Stage III A',
            'Zetor 1105',
            'Snaga prema ISO 2000/25 (kW/KS)',
            '55,6 / 76',
            'Broj cilindara',
            '4',
            'Nominalni broj obrtaja (o/min)',
            '2.200',
            'Turbo kompresor',
            'Da',
            'Zapremina motora (cm3)',
            '4.156',
            'Maks. obrtni moment (Nm) / rezerva (%)',
            '317 / 35'
        ],

        left2Title: 'Transmisija',
        table2: [
            'Tip',
            'Mehanička',
            'Reverzer',
            'Komanda ispod volana',
            'Menjač',
            'Potpuno sinhronizovan',
            'Broj stepeni prenosa (napred/nazad)',
            '12/12',
            'Maksimalna brzina kretanja (km/h)',
            '30',
        ],

        left3Title: 'Priključno vratilo',
        table3: [
            'Tip',
            'Zavisno / nezavisno',
            'Broj obrtaja (o/min)',
            '	540 / 1000',
        ],

        left4Title: 'Hidraulika',
        table4: [
            'Uređaj za priključenje “u tri tačke”',
            'kategorija CAT II',
            'Podizna moć na krajevima poluga (kN)',
            'standard 2600',
            'Kapacitet pumpe (l/min)',
            '50',
            'Broj priključaka spoljne hidraulike',
            '2 para + povratni vod',
        ],

        left5Title: 'Dimenzije',
        table5: [
            'Težina (kg)',
            '3.300',
            'Dužina/širina/visina (mm)',
            '4.702/1.970/2.580',
            'Međuosovinsko rastojanje (mm)',
            '2.210',
            'Zapremina rezervoara goriva (l)',
            '83',
            'Prednji točkovi',
            '11.2-24',
            'Zadnji točkovi',
            '12.4-36, opcija: 16.9-30',
        ],

        standardOprema1: 'Karakteristike',
        standardLi1: [
            ' - Zetor Major je u stanju da u potpunosti iskoristi svoju snagu zahvaljujući najboljoj mogućoj kombinaciji performansi motora i težine.',
            ' - Motor je odličan zbog male potrošnje goriva, velike pouzdanosti i jednostavne konstrukcije.'
        ],

        standardOprema2: 'Prednosti',
        standardLi2: [
            ' - Maksimalna sila podizanja Major CL 18kN',
            ' - Regulacija glatkog spuštanja',
            ' - Jednostavno i sigurno rukovanje dodatnom opremom',
            ' - Brzo spajanje',
            ' - Funkcija hidraulične brave prilikom transporta alata',
        ]
    },
]


export const both = [...Zetor];
export { Zetor }