const JohnDeere = [
    {
        _id: '1',
        nameUrl: 'john-deere-5045',
        productHeader: 'John Deere 5045 ',
        className: `john-deere-5045-img`,
        desc1: 'John Deere 5045D je atmosferski snažan motor sa nominalnim obrtajem od 2100. Ima jednostruko / dvostruko kvačilo, što omogućava glatko i lako funkcionisanje.',
        desc2: 'Podmazivanje gornje osovine u menjaču, mlaz za hlađenje klipnim raspršivačem i zadnja uljna osovina sa metalnom zaštitnom maskom su standardne karakteristike svih 5D modela što ga čini svestranim, izdržljivim i traktorom sa malim održavanjem.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'John Deere 5045',
        table1: [
            'Zapremina motora',
            '2.940 cm³',
            'Turbo Intercooler',
            'Stage IIIA',
            'Snaga motora',
            '33 kW/45 KS',
            'Rezervoar za gorivo',
            '60 l',
            'Tip transmisije',
            '8/4',
            'Maksimalna brzina',
            '35 km/h',
            'Hidraulična pumpa',
            '36 l/min.',
            'Broj pari izvoda hidraulike',
            '1 par.',
            'Podizna moć',
            '1400 kg.',
            'Točkovi',
            '6×28 Goodyear | 0x18 Goodyear',
            'Kočioni sistem',
            'Diskosne kočnice potopljene u ulju',
            'PTO',
            '540/540E o/min',
            'Dužina',
            '400 mm',
            'Širina',
            '950 mm',
            'Visina',
            '385 mm',
            'Težina',
            '825 kg',
        ],

    },
    {
        _id: '2',
        nameUrl: 'john-deere-5075',
        productHeader: 'John Deere 5075 ',
        className: `john-deere-5075-img`,
        desc1: 'Prednja osovina MFVD za teška opterećenja s ograničenim klizanjem obezbediće rukovaocima povećanu vuču vuče i poboljšanu vuču pri radu u klizavim uslovima',
        desc2: 'Komfor rukovaoca je važan bez obzira na primenu. Poboljšavajući modele 5E sa 3 cilindra, ručni gas je premešten na desnu konzolu. Ovo je 30,5 cm (12 inča) bliže rukovaocu i na dohvat ruke u odnosu na prethodno mesto na centralnoj konzoli.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'John Deere 5075',
        table1: [
            'Zapremina motora',
            '2.900cm³',
            'Turbo Intercooler',
            'Stage IIIA',
            'Snaga motora',
            '55 KW/75 KS',
            'Rezervoar za gorivo',
            '82 l',
            'Tip transmisije',
            '12/12 stepeni prenosa',
            'Maksimalna brzina',
            '35 km/h',
            'Hidraulična pumpa',
            '66 l/min',
            'Broj pari izvoda hidraulike',
            '2 para',
            'Podizna moć',
            '1.800 kg',
            'Kočioni sistem',
            'Diskosne kočnice potopljene u ulju',
            'PTO',
            '540/540E o/min',
            'Dužina',
            '3.640 mm',
            'Širina',
            '2.050 mm',
            'Težina',
            '3.320 kg',
        ],

    }
]

export const both = [...JohnDeere];
export { JohnDeere }