const Mahindra = [
    {
        _id: '1',
        nameUrl: 'mahindra-475-di-mkm',
        productHeader: 'Mahindra 475 DI',
        className: `mahindra-475-di-mkm-img`,
        desc1: 'Mahindra 475 DI MKM sastoji se od brojnih alata i karakteristika koji su isplativi za sve poljoprivredne svrhe.',
        desc2: 'Traktor Mahindra 475 DI MKM je funkcionalan, dizajniran je sa opuštenim sedištima i ručicama u jednostavnom produžetku. Napredna hidraulika omogućava udobno korišćenje rotavatora. Vredne karakteristike ovog modela traktora Mahindra prikazane su u nastavku.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Mahindra 475 DI MKM',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'MDI 2385 3A ; 30,9kW / 42 KS',
            'Broj cilindara',
            '4',
            'Zapremina motora u cm3',
            '2730',
            'Pumpa za ubrizgavanje goriva',
            'Rotaciona – BOSCH',
            'Sistem za hlađenje motora',
            'Voda – antifriz',
            'Menjač',
            'Mehanički sa reduktorom	',
            'Broj stepena prenosa, napred/nazad ',
            '8/2',
            'Priključno vratilo nezavisno, o/min',
            '540',
            'Kapacitet podizanja na krajevima poluga u kg',
            '1200',
            'Dimenzije guma: prednje / zadnje',
            '6.00X16 – 8 PLY / 12,4X28 – 12 PLY',
            'Težina sa balastom u kg',
            '2130',
            'Zapremina rezervoara za gorivo u litrama ',
            '50',
            'Dimenzije; dužina / širina / visina, u cm',
            '3510 / 1695 / 2172 (vrh auspuha)',
            'Klirens u mm',
            '460',
            'Kabina – opcija',
            'YARIŠ – Turska (290 kg)',
            'Upravljač ',
            'Hidraulični',
        ],
    },
    {
        _id: '2',
        nameUrl: 'mahindra-7030-di-4wd',
        productHeader: 'Mahindra 7030 DI',
        className: `mahindra-7030-img`,
        desc1: 'Traktor Mahindra 7030 u Indiji proizvodi Mahindra. Odlikuje ga Mahindra motor snage 70 ks (52 kV).',
        desc2: 'Traktor Mahindra 7030 u Indiji proizvodi Mahindra. Odlikuje ga Mahindra motor snage 70 ks (52 kV). Vredne karakteristike ovog modela traktora Mahindra prikazane su u nastavku.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Mahindra 7030 DI',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'NE 462R ; 47,9kW / 65 KS',
            'Broj cilindara',
            '4',
            'Zapremina motora u cm3',
            '3532',
            'Pumpa za ubrizgavanje goriva',
            'Rotaciona – BOSCH',
            'Sistem za hlađenje motora',
            'Voda – antifriz',
            'Menjač sa inverzorom',
            'Sinhronizovan sa reduktorom',
            'Broj stepena prenosa, napred/nazad ',
            '8/8',
            'Priključno vratilo nezavisno, o/min',
            '540',
            'Kapacitet podizanja na krajevima poluga u kg',
            '1800',
            'Dimenzije guma: prednje / zadnje',
            '11.2X24 – 8 PLY / 16.9X30 – 12 PLY',
            'Težina sa balastom u kg',
            '3135',
            'Zapremina rezervoara za gorivo u litrama ',
            '65',
            'Dimenzije; dužina / širina / visina, u cm',
            '3860 / 1956 / 2300 (vrh auspuha)',
            'Klirens u mm',
            '460',
            'Kabina – opcija',
            'YARIŠ – Turska (290 kg)',
            'Upravljač ',
            'Hidraulični',
        ],

    },
    {
        _id: '3',
        nameUrl: 'mahindra-595-di-turbo-mkm',
        productHeader: 'Mahindra 595 DI',
        className: `mahindra-595-img`,
        desc1: 'Mahindra 595 je model srednje teškog traktora snage 50 ks, koji je veoma poznat po neverovatnom odnosu cene i performansi.',
        desc2: 'Mahindra 595 DI TURBO pruža izuzetne performanse i ekonomičnu kilometražu na terenu. Ovaj model traktora srednje dužine najznačajnije se koristi za vučne radove i razne druge poljoprivredne radnje kao što su kultivacija, žetva, lokva i izvlačenje.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'Mahindra 595 DI TURBO',
        table1: [
            'Motor dizel-tip (kW / KS)',
            'MDI 3000 TC 3A ; 36,75kW / 50 KS',
            'Broj cilindara',
            '4',
            'Zapremina motora u cm3',
            '2524',
            'Pumpa za ubrizgavanje goriva',
            'Linijska – BOSCH',
            'Sistem za hlađenje motora',
            'Voda – antifriz',
            'Menjač',
            'mehanički sa reduktorom',
            'Broj stepena prenosa, napred/nazad ',
            '8/2',
            'Priključno vratilo nezavisno, o/min',
            '540',
            'Kapacitet podizanja na krajevima poluga u kg',
            '1650',
            'Dimenzije guma: prednje / zadnje',
            '6.00X16 – 8 PLY / 13,6X28 – 12 PLY',
            'Težina sa balastom u kg',
            '2220',
            'Zapremina rezervoara za gorivo u litrama ',
            '50',
            'Dimenzije; dužina / širina / visina, u cm',
            '3510 / 1730 / 2200 (vrh auspuha)',
            'Klirens u mm',
            '460',
            'Kabina – opcija',
            'YARIŠ – Turska (290 kg)',
            'Upravljač ',
            'Hidraulični',
        ],

    },
]

export const both = [...Mahindra];
export { Mahindra }
