const IMT = [
    {
        _id: '1',
        nameUrl: 'imt-565-2-di',
        productHeader: 'IMT 565.2 DI',
        className: `imt-565-2-di-img`,
        desc1: 'Ekonomični su za rad sa svim vrstama nošenih, polunošenih i vučenih oruđa sa priključnim merama kategorije I i II.',
        desc2: 'IMT 565 su namenjeni za sve srednje teške operacije u poljoprivredi, a omogućena im je upotreba i u šumarstvu, industriji, transportu i sl. Ekonomični su za rad sa svim vrstama nošenih, polunošenih i vučenih oruđa sa priključnim merama kategorije I i II.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'IMT 565.2 DI',
        table1: [
            'Model',
            'IMT 565.2 DI 4 WD',
            'Snaga motora KS (kW)',
            '63 (46,5), Euro 2',
            'Pogon ',
            '4 WD',
            'Izduvni sistem',
            'Vertikalni',
            'Prečistač vazduha',
            'Suv',
            'Spojnica ',
            'Dvostepena',
            'Menjački prenosnik',
            '8F+2R, mehanički sa klizajućim zupčanicima, centralni položaj komande',
            'PTO',
            'Jednostepeno, 540 o/min',
            'Zadnja osovina',
            'Direktan pogon',
            'Hidraulična pumpa',
            'Potopljena u ulju',
            'Maksimalna podizna moć (kg)',
            '2050',
            'Upravljač',
            'Hidraulički',
            'Prednji pneumatici',
            '9.5 x 24',
            'Zadnji pneumatici',
            '16.9 x 28',
            'Kočnice',
            'Potopljene u ulju',
            'Klateća poteznica ',
            'DA',
            'Prednji tegovi (kg)',
            'NE',
            'Zadnji tegovi (kg)',
            '2 x 45',
            'Cev za kipovanje',
            'NE',
            'Razvodni ventil',
            'Dva para hidrauličkih spojnica',
            'Kompresor',
            'DA',
            'Varijante',
            'Kabina, Sigurnosni luk',
        ],

    },
    {
        _id: '2',
        nameUrl: 'imt-549-3-di',
        productHeader: 'IMT 549.3 DI',
        className: `imt-549-3-di-img`,
        desc1: 'IMT 549.3 DI su univerzalni traktori koji sa sistemom od preko 100 priključnih oruđa',
        desc2: 'IMT 549.3 DI su univerzalni traktori koji sa sistemom od preko 100 priključnih oruđa, omogućavaju veoma raznovrsnu primenu u poljoprivredi, šumarstvu, građevinarstvu, transportu, industriji i sl. Traktori mogu da rade ekonomično sa svim vrstama nošenih, polunošenih i vučenih oruđa sa priključnim merama kategorije I.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'IMT 549.3 DI',
        table1: [
            'Model',
            'IMT 549.3 DI',
            'Snaga motora KS (kW)',
            '47 (35), Euro 3 A',
            'Pogon ',
            '4 WD',
            'Izduvni sistem',
            'Vertikalni',
            'Prečistač vazduha',
            'Suv',
            'Spojnica ',
            'Dvostepena',
            'Menjački prenosnik',
            '8F+2R, mehanički sa klizajućim zupčanicima, centralni položaj komande',
            'PTO',
            'Jednostepeno, 540 o/min',
            'Zadnja osovina',
            'Direktan pogon',
            'Hidraulična pumpa',
            'Potopljena u ulju',
            'Maksimalna podizna moć (kg)',
            '1700',
            'Upravljač',
            'Hidraulički',
            'Prednji pneumatici',
            '10.5 / 80 x 16',
            'Zadnji pneumatici',
            '13.6 x 28',
            'Kočnice',
            'Potopljene u ulju',
            'Klateća poteznica ',
            'DA',
            'Prednji tegovi (kg)',
            '4 × 25',
            'Zadnji tegovi (kg)',
            '2 × 40',
            'Cev za kipovanje',
            'NE',
            'Razvodni ventil',
            'Dva para hidrauličkih spojnica',
            'Kompresor',
            'DA',
            'Varijante',
            'Kabina, Sigurnosni luk',
        ],
    },
    {
        _id: '3',
        nameUrl: 'imt-539-2-di',
        productHeader: 'IMT 539.2 DI',
        className: `imt-539-2-di-img`,
        desc1: 'Traktor IMT 539.2 DI je traktor klasičnog dizajna, odličnih i pouzdanih performansi.',
        desc2: 'Traktor IMT 539.2 DI je traktor klasičnog dizajna, odličnih i pouzdanih performansi. Krasi ga jednostavnost pri rukovanju, kao i pouzdan hidraulični sistem.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'IMT 539.2 DI',
        table1: [
            'Model',
            'IMT 539.2 DI',
            'Snaga motora KS (kW)',
            '47 (35), Euro 2',
            'Pogon ',
            '2 WD',
            'Izduvni sistem',
            'Vertikalni',
            'Prečistač vazduha',
            'Uljni ',
            'Spojnica ',
            'Dvostepena',
            'Menjački prenosnik',
            '8F+2R, mehanički sa klizajućim zupčanicima, centralni položaj komande',
            'PTO',
            'Jednostepeno, 540 o/min',
            'Zadnja osovina',
            'Direktan pogon',
            'Hidraulična pumpa',
            'Potopljena u ulju',
            'Maksimalna podizna moć (kg)',
            '1100',
            'Upravljač',
            'Mehanički',
            'Prednji pneumatici',
            '6.00 × 16',
            'Zadnji pneumatici',
            '12.4 × 28',
            'Kočnice',
            'Doboš',
            'Klateća poteznica ',
            'DA',
            'Prednji tegovi (kg)',
            'NE',
            'Zadnji tegovi (kg)',
            'NE',
            'Cev za kipovanje',
            'DA',
            'Razvodni ventil',
            'NE',
            'Kompresor',
            'DA',
            'Varijante',
            'Kabina, Sigurnosni luk',
        ],

    },
    {
        _id: '4',
        nameUrl: 'imt-539-3-di',
        productHeader: 'IMT 539.3 DI',
        className: `imt-539-3-di-img`,
        desc1: 'Traktor IMT 539.3 DI je traktor klasičnog dizajna, odličnih i pouzdanih performansi.',
        desc2: 'Traktor IMT 539.3 DI je traktor klasičnog dizajna, odličnih i pouzdanih performansi. Krasi ga jednostavnost pri rukovanju, kao i pouzdan hidraulični sistem.',
        teh_kar: 'Tehničke Karakteristike',


        left1Title: 'IMT 539.3 DI',
        table1: [
            'Model',
            'IMT 539.3 DI',
            'Snaga motora KS (kW)',
            '47 (35), Euro 3 A',
            'Pogon ',
            '2 WD',
            'Izduvni sistem',
            'Vertikalni',
            'Prečistač vazduha',
            'Uljni ',
            'Spojnica ',
            'Dvostepena',
            'Menjački prenosnik',
            '8F+2R, mehanički sa klizajućim zupčanicima, centralni položaj komande',
            'PTO',
            'Jednostepeno, 540 o/min',
            'Zadnja osovina',
            'Direktan pogon',
            'Hidraulična pumpa',
            'Potopljena u ulju',
            'Maksimalna podizna moć (kg)',
            '1100',
            'Upravljač',
            'Mehanički',
            'Prednji pneumatici',
            '6.00 × 16',
            'Zadnji pneumatici',
            '12.4 × 28',
            'Kočnice',
            'Doboš',
            'Klateća poteznica ',
            'DA',
            'Prednji tegovi (kg)',
            'NE',
            'Zadnji tegovi (kg)',
            'NE',
            'Cev za kipovanje',
            'DA',
            'Razvodni ventil',
            'NE',
            'Kompresor',
            'DA',
            'Varijante',
            'Kabina, Sigurnosni luk',
        ],

    },
]








export const both = [...IMT];
export { IMT }